// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aws.KinesisAnalyticsV2.Inputs
{

    public sealed class ApplicationApplicationConfigurationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Code location and type parameters for the application. See `ApplicationCodeConfiguration` Block below.
        /// </summary>
        [Input("applicationCodeConfiguration", required: true)]
        public Input<Inputs.ApplicationApplicationConfigurationApplicationCodeConfigurationArgs> ApplicationCodeConfiguration { get; set; } = null!;

        /// <summary>
        /// Encryption configuration for the application. Use this to encrypt data at rest in the application. See `ApplicationEncryptionConfiguration` Block below.
        /// </summary>
        [Input("applicationEncryptionConfiguration")]
        public Input<Inputs.ApplicationApplicationConfigurationApplicationEncryptionConfigurationArgs>? ApplicationEncryptionConfiguration { get; set; }

        /// <summary>
        /// Snapshot configuration for a Flink-based application. See `ApplicationSnapshotConfiguration` Block below.
        /// </summary>
        [Input("applicationSnapshotConfiguration")]
        public Input<Inputs.ApplicationApplicationConfigurationApplicationSnapshotConfigurationArgs>? ApplicationSnapshotConfiguration { get; set; }

        /// <summary>
        /// Execution properties for a Flink-based application. See `EnvironmentProperties` Block below.
        /// </summary>
        [Input("environmentProperties")]
        public Input<Inputs.ApplicationApplicationConfigurationEnvironmentPropertiesArgs>? EnvironmentProperties { get; set; }

        /// <summary>
        /// Configuration of a Flink-based application. See `FlinkApplicationConfiguration` Block below.
        /// </summary>
        [Input("flinkApplicationConfiguration")]
        public Input<Inputs.ApplicationApplicationConfigurationFlinkApplicationConfigurationArgs>? FlinkApplicationConfiguration { get; set; }

        /// <summary>
        /// Starting properties for a Flink-based application. See `RunConfiguration` Block below.
        /// </summary>
        [Input("runConfiguration")]
        public Input<Inputs.ApplicationApplicationConfigurationRunConfigurationArgs>? RunConfiguration { get; set; }

        /// <summary>
        /// Configuration of a SQL-based application. See `SqlApplicationConfiguration` Block below.
        /// </summary>
        [Input("sqlApplicationConfiguration")]
        public Input<Inputs.ApplicationApplicationConfigurationSqlApplicationConfigurationArgs>? SqlApplicationConfiguration { get; set; }

        /// <summary>
        /// VPC configuration of a Flink-based application. See `VpcConfiguration` Block below.
        /// </summary>
        [Input("vpcConfiguration")]
        public Input<Inputs.ApplicationApplicationConfigurationVpcConfigurationArgs>? VpcConfiguration { get; set; }

        public ApplicationApplicationConfigurationArgs()
        {
        }
        public static new ApplicationApplicationConfigurationArgs Empty => new ApplicationApplicationConfigurationArgs();
    }
}
