// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aws.WafV2.Outputs
{

    [OutputType]
    public sealed class WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatch
    {
        /// <summary>
        /// Inspect all query arguments.
        /// </summary>
        public readonly Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchAllQueryArguments? AllQueryArguments;
        /// <summary>
        /// Inspect the request body as plain text. See Body below.
        /// </summary>
        public readonly Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchBody? Body;
        /// <summary>
        /// Inspect the request cookies. See Cookies below.
        /// </summary>
        public readonly Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchCookies? Cookies;
        /// <summary>
        /// Inspect a string containing the list of the request's header names, ordered as they appear in the web request. See Header Order below.
        /// </summary>
        public readonly ImmutableArray<Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchHeaderOrder> HeaderOrders;
        /// <summary>
        /// Inspect the request headers. See Headers below.
        /// </summary>
        public readonly ImmutableArray<Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchHeader> Headers;
        /// <summary>
        /// Match against the request's JA3 fingerprint (CloudFront and ALB only). See JA3 Fingerprint below.
        /// </summary>
        public readonly Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchJa3Fingerprint? Ja3Fingerprint;
        /// <summary>
        /// Match against the request's JA4 fingerprint (CloudFront and ALB only). See JA4 Fingerprint below.
        /// </summary>
        public readonly Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchJa4Fingerprint? Ja4Fingerprint;
        /// <summary>
        /// Inspect the request body as JSON. See JSON Body below.
        /// </summary>
        public readonly Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchJsonBody? JsonBody;
        /// <summary>
        /// Inspect the HTTP method.
        /// </summary>
        public readonly Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchMethod? Method;
        /// <summary>
        /// Inspect the query string.
        /// </summary>
        public readonly Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchQueryString? QueryString;
        /// <summary>
        /// Inspect a single header. See Single Header below.
        /// </summary>
        public readonly Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchSingleHeader? SingleHeader;
        /// <summary>
        /// Inspect a single query argument. See Single Query Argument below.
        /// </summary>
        public readonly Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchSingleQueryArgument? SingleQueryArgument;
        /// <summary>
        /// Inspect fragments of the request URI. See URI Fragment below.
        /// </summary>
        public readonly Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchUriFragment? UriFragment;
        /// <summary>
        /// Inspect the request URI path.
        /// </summary>
        public readonly Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchUriPath? UriPath;

        [OutputConstructor]
        private WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatch(
            Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchAllQueryArguments? allQueryArguments,

            Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchBody? body,

            Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchCookies? cookies,

            ImmutableArray<Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchHeaderOrder> headerOrders,

            ImmutableArray<Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchHeader> headers,

            Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchJa3Fingerprint? ja3Fingerprint,

            Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchJa4Fingerprint? ja4Fingerprint,

            Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchJsonBody? jsonBody,

            Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchMethod? method,

            Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchQueryString? queryString,

            Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchSingleHeader? singleHeader,

            Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchSingleQueryArgument? singleQueryArgument,

            Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchUriFragment? uriFragment,

            Outputs.WebAclRuleStatementNotStatementStatementManagedRuleGroupStatementScopeDownStatementSizeConstraintStatementFieldToMatchUriPath? uriPath)
        {
            AllQueryArguments = allQueryArguments;
            Body = body;
            Cookies = cookies;
            HeaderOrders = headerOrders;
            Headers = headers;
            Ja3Fingerprint = ja3Fingerprint;
            Ja4Fingerprint = ja4Fingerprint;
            JsonBody = jsonBody;
            Method = method;
            QueryString = queryString;
            SingleHeader = singleHeader;
            SingleQueryArgument = singleQueryArgument;
            UriFragment = uriFragment;
            UriPath = uriPath;
        }
    }
}
