// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aws.Ec2.Outputs
{

    [OutputType]
    public sealed class FleetLaunchTemplateConfigLaunchTemplateSpecification
    {
        /// <summary>
        /// The ID of the launch template.
        /// </summary>
        public readonly string? LaunchTemplateId;
        /// <summary>
        /// The name of the launch template.
        /// </summary>
        public readonly string? LaunchTemplateName;
        /// <summary>
        /// The launch template version number, `$Latest`, or `$Default.`
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private FleetLaunchTemplateConfigLaunchTemplateSpecification(
            string? launchTemplateId,

            string? launchTemplateName,

            string version)
        {
            LaunchTemplateId = launchTemplateId;
            LaunchTemplateName = launchTemplateName;
            Version = version;
        }
    }
}
