// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.policypacks.aws.docdb;

import com.pulumi.core.annotations.PolicyResourceType;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Map;


@PolicyResourceType(type="aws:docdb/clusterInstance:ClusterInstance")
public final class ClusterInstance extends com.pulumi.resources.PolicyResource {

    /**
     * Specifies whether any database modifications
     * are applied immediately, or during the next maintenance window. Default is`false`.
     * 
     */
    public Boolean applyImmediately;



    /**
     * Amazon Resource Name (ARN) of cluster instance
     * 
     */
    public String arn;



    /**
     * This parameter does not apply to Amazon DocumentDB. Amazon DocumentDB does not perform minor version upgrades regardless of the value set (see [docs](https://docs.aws.amazon.com/documentdb/latest/developerguide/API_DBInstance.html)). Default `true`.
     * 
     */
    public Boolean autoMinorVersionUpgrade;



    /**
     * The EC2 Availability Zone that the DB instance is created in. See [docs](https://docs.aws.amazon.com/documentdb/latest/developerguide/API_CreateDBInstance.html) about the details.
     * 
     */
    public String availabilityZone;



    /**
     * The identifier of the certificate authority (CA) certificate for the DB instance.
     * 
     */
    public String caCertIdentifier;



    /**
     * The identifier of the `aws.docdb.Cluster` in which to launch this instance.
     * 
     */
    public String clusterIdentifier;



    /**
     * Copy all DB instance `tags` to snapshots. Default is `false`.
     * 
     */
    public Boolean copyTagsToSnapshot;



    /**
     * The DB subnet group to associate with this DB instance.
     * 
     */
    public String dbSubnetGroupName;



    /**
     * The region-unique, immutable identifier for the DB instance.
     * 
     */
    public String dbiResourceId;



    /**
     * A value that indicates whether to enable Performance Insights for the DB Instance. Default `false`. See [docs] (https://docs.aws.amazon.com/documentdb/latest/developerguide/performance-insights.html) about the details.
     * 
     */
    public Boolean enablePerformanceInsights;



    /**
     * The DNS address for this instance. May not be writable
     * 
     */
    public String endpoint;



    /**
     * The name of the database engine to be used for the DocumentDB instance. Defaults to `docdb`. Valid Values: `docdb`.
     * 
     */
    public String engine;



    /**
     * The database engine version
     * 
     */
    public String engineVersion;



    /**
     * The identifier for the DocumentDB instance, if omitted, the provider will assign a random, unique identifier.
     * 
     */
    public String identifier;



    /**
     * Creates a unique identifier beginning with the specified prefix. Conflicts with `identifier`.
     * 
     */
    public String identifierPrefix;



    /**
     * The instance class to use. For details on CPU and memory, see [Scaling for DocumentDB Instances](https://docs.aws.amazon.com/documentdb/latest/developerguide/db-cluster-manage-performance.html#db-cluster-manage-scaling-instance).
     * DocumentDB currently supports the below instance classes.
     * Please see [AWS Documentation](https://docs.aws.amazon.com/documentdb/latest/developerguide/db-instance-classes.html#db-instance-class-specs) for complete details.
     * - db.r6g.large
     * - db.r6g.xlarge
     * - db.r6g.2xlarge
     * - db.r6g.4xlarge
     * - db.r6g.8xlarge
     * - db.r6g.12xlarge
     * - db.r6g.16xlarge
     * - db.r5.large
     * - db.r5.xlarge
     * - db.r5.2xlarge
     * - db.r5.4xlarge
     * - db.r5.12xlarge
     * - db.r5.24xlarge
     * - db.r4.large
     * - db.r4.xlarge
     * - db.r4.2xlarge
     * - db.r4.4xlarge
     * - db.r4.8xlarge
     * - db.r4.16xlarge
     * - db.t4g.medium
     * - db.t3.medium
     * 
     */
    public String instanceClass;



    /**
     * The ARN for the KMS encryption key if one is set to the cluster.
     * 
     */
    public String kmsKeyId;



    /**
     * The KMS key identifier is the key ARN, key ID, alias ARN, or alias name for the KMS key. If you do not specify a value for PerformanceInsightsKMSKeyId, then Amazon DocumentDB uses your default KMS key.
     * 
     */
    public String performanceInsightsKmsKeyId;



    /**
     * The database port
     * 
     */
    public Integer port;



    /**
     * The daily time range during which automated backups are created if automated backups are enabled.
     * 
     */
    public String preferredBackupWindow;



    /**
     * The window to perform maintenance in.
     * Syntax: &#34;ddd:hh24:mi-ddd:hh24:mi&#34;. Eg: &#34;Mon:00:00-Mon:03:00&#34;.
     * 
     */
    public String preferredMaintenanceWindow;



    /**
     * Default 0. Failover Priority setting on instance level. The reader who has lower tier has higher priority to get promoter to writer.
     * 
     */
    public Integer promotionTier;



    public Boolean publiclyAccessible;



    /**
     * Specifies whether the DB cluster is encrypted.
     * 
     */
    public Boolean storageEncrypted;



    /**
     * A map of tags to assign to the instance. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
     * 
     */
    public Map<String,String> tags;



    /**
     * A map of tags assigned to the resource, including those inherited from the provider `default_tags` configuration block.
     * 
     * @deprecated
     * Please use `tags` instead.
     * 
     */
    @Deprecated /* Please use `tags` instead. */
    public Map<String,String> tagsAll;



    /**
     * Boolean indicating if this instance is writable. `False` indicates this instance is a read replica.
     * 
     */
    public Boolean writer;



}
