// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.PolicyPacks.Aws.Route53RecoveryControl
{
    [PolicyResourceType("aws:route53recoverycontrol/controlPanel:ControlPanel")]
    public sealed class ControlPanel : global::Pulumi.PolicyResource
    {
        /// <summary>
        /// ARN of the control panel.
        /// </summary>
        [Input("arn")]
        public string? Arn;

        /// <summary>
        /// ARN of the cluster in which this control panel will reside.
        /// </summary>
        [Input("clusterArn")]
        public string? ClusterArn;

        /// <summary>
        /// Whether a control panel is default.
        /// </summary>
        [Input("defaultControlPanel")]
        public bool? DefaultControlPanel;

        /// <summary>
        /// Name describing the control panel.
        /// </summary>
        [Input("name")]
        public string? Name;

        /// <summary>
        /// Number routing controls in a control panel.
        /// </summary>
        [Input("routingControlCount")]
        public int? RoutingControlCount;

        /// <summary>
        /// Status of control panel: `PENDING` when it is being created/updated, `PENDING_DELETION` when it is being deleted, and `DEPLOYED` otherwise.
        /// </summary>
        [Input("status")]
        public string? Status;
    }
}
