// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.PolicyPacks.Aws.CodePipeline.Inputs
{
    public sealed class PipelineStageOnSuccessConditionArgs
    {
        /// <summary>
        /// The action to be done when the condition is met. For example, rolling back an execution for a failure condition. Possible values are `ROLLBACK`, `FAIL`, `RETRY` and `SKIP`.
        /// </summary>
        [Input("result")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<string> _mResult;

        public string? Result => _mResult.GetValue("result");

        /// <summary>
        /// The rules that make up the condition. Defined as a `rule` block below.
        /// </summary>
        [Input("rules")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<List<Inputs.PipelineStageOnSuccessConditionRuleArgs>> _mRules;

        public List<Inputs.PipelineStageOnSuccessConditionRuleArgs>? Rules => _mRules.GetValue("rules");
    }
}
