// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aws.AppSync.Inputs
{

    public sealed class DataSourceRelationalDatabaseConfigGetArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Amazon RDS HTTP endpoint configuration. See HTTP Endpoint Config.
        /// </summary>
        [Input("httpEndpointConfig")]
        public Input<Inputs.DataSourceRelationalDatabaseConfigHttpEndpointConfigGetArgs>? HttpEndpointConfig { get; set; }

        /// <summary>
        /// Source type for the relational database. Valid values: `RDS_HTTP_ENDPOINT`.
        /// </summary>
        [Input("sourceType")]
        public Input<string>? SourceType { get; set; }

        public DataSourceRelationalDatabaseConfigGetArgs()
        {
        }
    }
}
