// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.PolicyPacks.Aws.CloudFormation
{
    [PolicyResourceType("aws:cloudformation/StackSetInstanceDeploymentTargets:StackSetInstanceDeploymentTargets")]
    public sealed class StackSetInstanceDeploymentTargets
    {
        /// <summary>
        /// Limit deployment targets to individual accounts or include additional accounts with provided OUs. Valid values: `INTERSECTION`, `DIFFERENCE`, `UNION`, `NONE`.
        /// </summary>
        [Input("accountFilterType")]
        public string? AccountFilterType;

        /// <summary>
        /// List of accounts to deploy stack set updates.
        /// </summary>
        [Input("accounts")]
        public List<string>? Accounts;

        /// <summary>
        /// S3 URL of the file containing the list of accounts.
        /// </summary>
        [Input("accountsUrl")]
        public string? AccountsUrl;

        /// <summary>
        /// Organization root ID or organizational unit (OU) IDs to which StackSets deploys.
        /// </summary>
        [Input("organizationalUnitIds")]
        public List<string>? OrganizationalUnitIds;
    }
}
