provider: aws
lint: false
major-version: 7
parallel: 1
shards: 8
timeout: 150
generate-nightly-test-workflow: true
providerVersion: github.com/hashicorp/terraform-provider-aws/version.ProviderVersion
buildProviderPre: "VERSION=${VERSION_GENERIC} ./scripts/minimal_schema.sh"
esc:
    enabled: true
env:
    PULUMI_MISSING_DOCS_ERROR: true
    AWS_REGION: "us-west-2"
    OIDC_ROLE_ARN: ${{ secrets.OIDC_ROLE_ARN }}
makeTemplate: bridged
checkoutSubmodules: true
freeDiskSpaceBeforeBuild: true
freeDiskSpaceBeforeSdkBuild: true
freeDiskSpaceBeforeTest: true
# TODO: remove XrunUpstreamTools flag after work to add docs replacement strategies to resources.go is completed
# Tracked in in https://github.com/pulumi/pulumi-aws/issues/2757
XrunUpstreamTools: true
# Use `pulumi convert` for translating examples from TF to Pulumi.
pulumiConvert: 1
allowMissingDocs: false
goBuildParallelism: 2
aws: true
releaseVerification:
    nodejs: examples/release-verification
    python: examples/webserver-py
    dotnet: examples/webserver-cs
    go: examples/webserver-go
autoMergeProviderUpgrades: false
