provider: aws
lint: false
major-version: 6
parallel: 1
timeout: 150
generate-nightly-test-workflow: true
providerVersion: github.com/hashicorp/terraform-provider-aws/version.ProviderVersion
toolVersions:
  dotnet: "6.0.x"
  go: "1.23.x"
  java: "11"
  gradle: "7.6"
  nodejs: "20.x"
  pulumi: "dev"
  python: "3.11.8"
env:
  PULUMI_MISSING_DOCS_ERROR: true
  AWS_REGION: "us-west-2"
  OIDC_ROLE_ARN: ${{ secrets.OIDC_ROLE_ARN }}
makeTemplate: bridged
checkoutSubmodules: true
freeDiskSpaceBeforeBuild: true
freeDiskSpaceBeforeSdkBuild: true
freeDiskSpaceBeforeTest: true
# TODO: remove XrunUpstreamTools flag after work to add docs replacement strategies to resources.go is completed
# Tracked in in https://github.com/pulumi/pulumi-aws/issues/2757
XrunUpstreamTools: true
plugins:
  - name: archive
    version: "0.0.1"
  - name: tls
    version: "4.10.0"
  - name: github
    version: "4.10.0"
  - name: kubernetes
    version: "4.11.0"
  - name: "null"
    version: "0.0.3"
  - name: "local"
    version: "0.1.0"
  - name: random
    version: "4.8.2"
  - name: github
    version: "5.14.0"
  - name: std
    version: "1.6.2"
  - name: terraform
    version: "1.0.17"
    kind: converter
# Use `pulumi convert` for translating examples from TF to Pulumi.
pulumiConvert: 1
goBuildParallelism: 2
actions:
  preTest:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-region: ${{ env.AWS_REGION }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-duration-seconds: 7200
        role-session-name: aws@githubActions
        role-to-assume: ${{ secrets.AWS_CI_ROLE_ARN }}
    - name: Make upstream
      run: make upstream

extraTests:
  go_test_shim:
    name: Run test of provider shim
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        swap-storage: false
        tool-cache: false
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        ref: ${{ env.PR_COMMIT_SHA }}
        submodules: true
    - uses: pulumi/provider-version-action@v1
      with:
        set-env: 'PROVIDER_VERSION'
    - name: Setup tools
      uses: ./.github/actions/setup-tools
      with:
        tools: pulumictl, pulumi, go
    - name: Prepare local workspace
      run: make prepare_local_workspace
    - name: go test
      run: |
        cd upstream
        go get github.com/hashicorp/aws-sdk-go-base@v1.1.0
        cd shim
        go test -v -coverprofile="coverage.txt" .
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      env:
       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  upstream_lint:
    name: Run upstream provider-lint
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        swap-storage: false
        tool-cache: false
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        ref: ${{ env.PR_COMMIT_SHA }}
        submodules: true
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23.x"
        cache: false
    - name: Prepare local workspace
      run: make prepare_local_workspace
    - name: upstream lint
      run: |
        cd upstream
        make provider-lint
