run:
  timeout: 15m
  skip-files:
    - 'schema.go'
    - 'pulumiManifest.go'

linters:
  enable-all: false
  enable:
    - deadcode
    - errcheck
    - goconst
    - golint
    - gofmt
    - gosec
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - structcheck
    - unconvert
    - varcheck
  disable:
    - staticcheck
    - megacheck
