// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aws.opensearch.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetServerlessSecurityPolicyPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetServerlessSecurityPolicyPlainArgs Empty = new GetServerlessSecurityPolicyPlainArgs();

    @Import(name="name", required=true)
    private String name;

    public String name() {
        return this.name;
    }

    @Import(name="region")
    private @Nullable String region;

    public Optional<String> region() {
        return Optional.ofNullable(this.region);
    }

    @Import(name="type", required=true)
    private String type;

    public String type() {
        return this.type;
    }

    private GetServerlessSecurityPolicyPlainArgs() {}

    private GetServerlessSecurityPolicyPlainArgs(GetServerlessSecurityPolicyPlainArgs $) {
        this.name = $.name;
        this.region = $.region;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetServerlessSecurityPolicyPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetServerlessSecurityPolicyPlainArgs $;

        public Builder() {
            $ = new GetServerlessSecurityPolicyPlainArgs();
        }

        public Builder(GetServerlessSecurityPolicyPlainArgs defaults) {
            $ = new GetServerlessSecurityPolicyPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder name(String name) {
            $.name = name;
            return this;
        }

        public Builder region(@Nullable String region) {
            $.region = region;
            return this;
        }

        public Builder type(String type) {
            $.type = type;
            return this;
        }

        public GetServerlessSecurityPolicyPlainArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetServerlessSecurityPolicyPlainArgs", "name");
            }
            if ($.type == null) {
                throw new MissingRequiredPropertyException("GetServerlessSecurityPolicyPlainArgs", "type");
            }
            return $;
        }
    }

}
