// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.policypacks.aws.appfabric;

import com.pulumi.policypacks.aws.appfabric.IngestionDestinationDestinationConfigurationAuditLogDestination;


public final class IngestionDestinationDestinationConfigurationAuditLog {

    /**
     * Contains information about an audit log destination. Only one destination (Firehose Stream) or (S3 Bucket) can be specified.
     * 
     */
    public IngestionDestinationDestinationConfigurationAuditLogDestination destination;



}
