// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.PolicyPacks.Aws.Quicksight
{
    [PolicyResourceType("aws:quicksight/template:Template")]
    public sealed class Template : global::Pulumi.PolicyResourceOutput
    {
        /// <summary>
        /// ARN of the template.
        /// </summary>
        [Input("arn")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<string> _mArn;

        public string? Arn => _mArn.GetValue("arn");

        /// <summary>
        /// AWS account ID.
        /// </summary>
        [Input("awsAccountId")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<string> _mAwsAccountId;

        public string? AwsAccountId => _mAwsAccountId.GetValue("awsAccountId");

        /// <summary>
        /// The time that the template was created.
        /// </summary>
        [Input("createdTime")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<string> _mCreatedTime;

        public string? CreatedTime => _mCreatedTime.GetValue("createdTime");

        /// <summary>
        /// The time that the template was last updated.
        /// </summary>
        [Input("lastUpdatedTime")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<string> _mLastUpdatedTime;

        public string? LastUpdatedTime => _mLastUpdatedTime.GetValue("lastUpdatedTime");

        /// <summary>
        /// Display name for the template.
        /// </summary>
        [Input("name")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<string> _mName;

        public string? Name => _mName.GetValue("name");

        /// <summary>
        /// A set of resource permissions on the template. Maximum of 64 items. See permissions.
        /// </summary>
        [Input("permissions")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<List<Outputs.TemplatePermission>> _mPermissions;

        public List<Outputs.TemplatePermission>? Permissions => _mPermissions.GetValue("permissions");

        /// <summary>
        /// The entity that you are using as a source when you create the template (analysis or template). Only one of `definition` or `source_entity` should be configured. See source_entity.
        /// </summary>
        [Input("sourceEntity")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<Outputs.TemplateSourceEntity> _mSourceEntity;

        public Outputs.TemplateSourceEntity? SourceEntity => _mSourceEntity.GetValue("sourceEntity");

        /// <summary>
        /// Amazon Resource Name (ARN) of an analysis or template that was used to create this template.
        /// </summary>
        [Input("sourceEntityArn")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<string> _mSourceEntityArn;

        public string? SourceEntityArn => _mSourceEntityArn.GetValue("sourceEntityArn");

        /// <summary>
        /// The template creation status.
        /// </summary>
        [Input("status")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<string> _mStatus;

        public string? Status => _mStatus.GetValue("status");

        /// <summary>
        /// Key-value map of resource tags. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
        /// </summary>
        [Input("tags")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<Dictionary<string, string>> _mTags;

        public Dictionary<string, string>? Tags => _mTags.GetValue("tags");

        /// <summary>
        /// A map of tags assigned to the resource, including those inherited from the provider `default_tags` configuration block.
        /// </summary>
        [Input("tagsAll")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<Dictionary<string, string>> _mTagsAll;

        public Dictionary<string, string>? TagsAll => _mTagsAll.GetValue("tagsAll");

        /// <summary>
        /// Identifier for the template.
        /// </summary>
        [Input("templateId")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<string> _mTemplateId;

        public string? TemplateId => _mTemplateId.GetValue("templateId");

        /// <summary>
        /// A description of the current template version being created/updated.
        /// 
        /// The following arguments are optional:
        /// </summary>
        [Input("versionDescription")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<string> _mVersionDescription;

        public string? VersionDescription => _mVersionDescription.GetValue("versionDescription");

        /// <summary>
        /// The version number of the template version.
        /// </summary>
        [Input("versionNumber")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<int> _mVersionNumber;

        public int? VersionNumber => _mVersionNumber.GetValue("versionNumber");
    }

    [PolicyResourceType("aws:quicksight/template:Template")]
    public sealed class TemplateArgs : global::Pulumi.PolicyResourceInput
    {
        /// <summary>
        /// AWS account ID.
        /// </summary>
        [Input("awsAccountId")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<string> _mAwsAccountId;

        public string? AwsAccountId => _mAwsAccountId.GetValue("awsAccountId");

        /// <summary>
        /// Display name for the template.
        /// </summary>
        [Input("name")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<string> _mName;

        public string? Name => _mName.GetValue("name");

        /// <summary>
        /// A set of resource permissions on the template. Maximum of 64 items. See permissions.
        /// </summary>
        [Input("permissions")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<List<Inputs.TemplatePermissionArgs>> _mPermissions;

        public List<Inputs.TemplatePermissionArgs>? Permissions => _mPermissions.GetValue("permissions");

        /// <summary>
        /// The entity that you are using as a source when you create the template (analysis or template). Only one of `definition` or `source_entity` should be configured. See source_entity.
        /// </summary>
        [Input("sourceEntity")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<Inputs.TemplateSourceEntityArgs> _mSourceEntity;

        public Inputs.TemplateSourceEntityArgs? SourceEntity => _mSourceEntity.GetValue("sourceEntity");

        /// <summary>
        /// Key-value map of resource tags. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
        /// </summary>
        [Input("tags")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<Dictionary<string, string>> _mTags;

        public Dictionary<string, string>? Tags => _mTags.GetValue("tags");

        /// <summary>
        /// Identifier for the template.
        /// </summary>
        [Input("templateId")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<string> _mTemplateId;

        public string? TemplateId => _mTemplateId.GetValue("templateId");

        /// <summary>
        /// A description of the current template version being created/updated.
        /// 
        /// The following arguments are optional:
        /// </summary>
        [Input("versionDescription")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<string> _mVersionDescription;

        public string? VersionDescription => _mVersionDescription.GetValue("versionDescription");
    }
}
