// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.PolicyPacks.Aws.Connect
{
    [PolicyResourceType("aws:connect/instance:Instance")]
    public sealed class Instance : global::Pulumi.PolicyResource
    {
        /// <summary>
        /// Amazon Resource Name (ARN) of the instance.
        /// </summary>
        [Input("arn")]
        public string? Arn;

        /// <summary>
        /// Specifies whether auto resolve best voices is enabled. Defaults to `true`.
        /// </summary>
        [Input("autoResolveBestVoicesEnabled")]
        public bool? AutoResolveBestVoicesEnabled;

        /// <summary>
        /// Specifies whether contact flow logs are enabled. Defaults to `false`.
        /// </summary>
        [Input("contactFlowLogsEnabled")]
        public bool? ContactFlowLogsEnabled;

        /// <summary>
        /// Specifies whether contact lens is enabled. Defaults to `true`.
        /// </summary>
        [Input("contactLensEnabled")]
        public bool? ContactLensEnabled;

        /// <summary>
        /// When the instance was created.
        /// </summary>
        [Input("createdTime")]
        public string? CreatedTime;

        /// <summary>
        /// The identifier for the directory if identity_management_type is `EXISTING_DIRECTORY`.
        /// </summary>
        [Input("directoryId")]
        public string? DirectoryId;

        /// <summary>
        /// Specifies whether early media for outbound calls is enabled . Defaults to `true` if outbound calls is enabled.
        /// </summary>
        [Input("earlyMediaEnabled")]
        public bool? EarlyMediaEnabled;

        /// <summary>
        /// Specifies the identity management type attached to the instance. Allowed Values are: `SAML`, `CONNECT_MANAGED`, `EXISTING_DIRECTORY`.
        /// </summary>
        [Input("identityManagementType")]
        public string? IdentityManagementType;

        /// <summary>
        /// Specifies whether inbound calls are enabled.
        /// </summary>
        [Input("inboundCallsEnabled")]
        public bool? InboundCallsEnabled;

        /// <summary>
        /// Specifies the name of the instance. Required if `directory_id` not specified.
        /// </summary>
        [Input("instanceAlias")]
        public string? InstanceAlias;

        /// <summary>
        /// Specifies whether multi-party calls/conference is enabled. Defaults to `false`.
        /// </summary>
        [Input("multiPartyConferenceEnabled")]
        public bool? MultiPartyConferenceEnabled;

        /// <summary>
        /// Specifies whether outbound calls are enabled.
        /// </summary>
        [Input("outboundCallsEnabled")]
        public bool? OutboundCallsEnabled;

        /// <summary>
        /// The service role of the instance.
        /// </summary>
        [Input("serviceRole")]
        public string? ServiceRole;

        /// <summary>
        /// The state of the instance.
        /// </summary>
        [Input("status")]
        public string? Status;

        /// <summary>
        /// Tags to apply to the Instance. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
        /// &lt;!-- * `use_custom_tts_voices` - (Optional) Whether use custom tts voices is enabled. Defaults to `false` --&gt;
        /// </summary>
        [Input("tags")]
        public Dictionary<string, string>? Tags;

        /// <summary>
        /// A map of tags assigned to the resource, including those inherited from the provider `default_tags` configuration block.
        /// </summary>
        [Input("tagsAll")]
        public Dictionary<string, string>? TagsAll;
    }
}
