// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export class PatchBaseline extends pulumi.CustomResource {
    /**
     * Get an existing PatchBaseline resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PatchBaselineState, opts?: pulumi.CustomResourceOptions): PatchBaseline {
        return new PatchBaseline(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'aws:ssm/patchBaseline:PatchBaseline';

    /**
     * Returns true if the given object is an instance of PatchBaseline.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PatchBaseline {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PatchBaseline.__pulumiType;
    }

    declare public readonly approvalRules: pulumi.Output<outputs.ssm.PatchBaselineApprovalRule[] | undefined>;
    declare public readonly approvedPatches: pulumi.Output<string[] | undefined>;
    declare public readonly approvedPatchesComplianceLevel: pulumi.Output<string | undefined>;
    declare public readonly approvedPatchesEnableNonSecurity: pulumi.Output<boolean | undefined>;
    declare public /*out*/ readonly arn: pulumi.Output<string>;
    declare public readonly availableSecurityUpdatesComplianceStatus: pulumi.Output<string>;
    declare public readonly description: pulumi.Output<string | undefined>;
    declare public readonly globalFilters: pulumi.Output<outputs.ssm.PatchBaselineGlobalFilter[] | undefined>;
    declare public /*out*/ readonly json: pulumi.Output<string>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly operatingSystem: pulumi.Output<string | undefined>;
    declare public readonly region: pulumi.Output<string>;
    declare public readonly rejectedPatches: pulumi.Output<string[] | undefined>;
    declare public readonly rejectedPatchesAction: pulumi.Output<string>;
    declare public readonly sources: pulumi.Output<outputs.ssm.PatchBaselineSource[] | undefined>;
    declare public readonly tags: pulumi.Output<{[key: string]: string} | undefined>;
    declare public /*out*/ readonly tagsAll: pulumi.Output<{[key: string]: string}>;

    /**
     * Create a PatchBaseline resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PatchBaselineArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PatchBaselineArgs | PatchBaselineState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PatchBaselineState | undefined;
            resourceInputs["approvalRules"] = state?.approvalRules;
            resourceInputs["approvedPatches"] = state?.approvedPatches;
            resourceInputs["approvedPatchesComplianceLevel"] = state?.approvedPatchesComplianceLevel;
            resourceInputs["approvedPatchesEnableNonSecurity"] = state?.approvedPatchesEnableNonSecurity;
            resourceInputs["arn"] = state?.arn;
            resourceInputs["availableSecurityUpdatesComplianceStatus"] = state?.availableSecurityUpdatesComplianceStatus;
            resourceInputs["description"] = state?.description;
            resourceInputs["globalFilters"] = state?.globalFilters;
            resourceInputs["json"] = state?.json;
            resourceInputs["name"] = state?.name;
            resourceInputs["operatingSystem"] = state?.operatingSystem;
            resourceInputs["region"] = state?.region;
            resourceInputs["rejectedPatches"] = state?.rejectedPatches;
            resourceInputs["rejectedPatchesAction"] = state?.rejectedPatchesAction;
            resourceInputs["sources"] = state?.sources;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["tagsAll"] = state?.tagsAll;
        } else {
            const args = argsOrState as PatchBaselineArgs | undefined;
            resourceInputs["approvalRules"] = args?.approvalRules;
            resourceInputs["approvedPatches"] = args?.approvedPatches;
            resourceInputs["approvedPatchesComplianceLevel"] = args?.approvedPatchesComplianceLevel;
            resourceInputs["approvedPatchesEnableNonSecurity"] = args?.approvedPatchesEnableNonSecurity;
            resourceInputs["availableSecurityUpdatesComplianceStatus"] = args?.availableSecurityUpdatesComplianceStatus;
            resourceInputs["description"] = args?.description;
            resourceInputs["globalFilters"] = args?.globalFilters;
            resourceInputs["name"] = args?.name;
            resourceInputs["operatingSystem"] = args?.operatingSystem;
            resourceInputs["region"] = args?.region;
            resourceInputs["rejectedPatches"] = args?.rejectedPatches;
            resourceInputs["rejectedPatchesAction"] = args?.rejectedPatchesAction;
            resourceInputs["sources"] = args?.sources;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["arn"] = undefined /*out*/;
            resourceInputs["json"] = undefined /*out*/;
            resourceInputs["tagsAll"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PatchBaseline.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering PatchBaseline resources.
 */
export interface PatchBaselineState {
    approvalRules?: pulumi.Input<pulumi.Input<inputs.ssm.PatchBaselineApprovalRule>[]>;
    approvedPatches?: pulumi.Input<pulumi.Input<string>[]>;
    approvedPatchesComplianceLevel?: pulumi.Input<string>;
    approvedPatchesEnableNonSecurity?: pulumi.Input<boolean>;
    arn?: pulumi.Input<string>;
    availableSecurityUpdatesComplianceStatus?: pulumi.Input<string>;
    description?: pulumi.Input<string>;
    globalFilters?: pulumi.Input<pulumi.Input<inputs.ssm.PatchBaselineGlobalFilter>[]>;
    json?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    operatingSystem?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    rejectedPatches?: pulumi.Input<pulumi.Input<string>[]>;
    rejectedPatchesAction?: pulumi.Input<string>;
    sources?: pulumi.Input<pulumi.Input<inputs.ssm.PatchBaselineSource>[]>;
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    tagsAll?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}

/**
 * The set of arguments for constructing a PatchBaseline resource.
 */
export interface PatchBaselineArgs {
    approvalRules?: pulumi.Input<pulumi.Input<inputs.ssm.PatchBaselineApprovalRule>[]>;
    approvedPatches?: pulumi.Input<pulumi.Input<string>[]>;
    approvedPatchesComplianceLevel?: pulumi.Input<string>;
    approvedPatchesEnableNonSecurity?: pulumi.Input<boolean>;
    availableSecurityUpdatesComplianceStatus?: pulumi.Input<string>;
    description?: pulumi.Input<string>;
    globalFilters?: pulumi.Input<pulumi.Input<inputs.ssm.PatchBaselineGlobalFilter>[]>;
    name?: pulumi.Input<string>;
    operatingSystem?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    rejectedPatches?: pulumi.Input<pulumi.Input<string>[]>;
    rejectedPatchesAction?: pulumi.Input<string>;
    sources?: pulumi.Input<pulumi.Input<inputs.ssm.PatchBaselineSource>[]>;
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}
