// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aws.WafV2.Inputs
{

    public sealed class RuleGroupRuleStatementOrStatementStatementNotStatementArgs : global::Pulumi.ResourceArgs
    {
        [Input("statements", required: true)]
        private InputList<Inputs.RuleGroupRuleStatementOrStatementStatementNotStatementStatementArgs>? _statements;
        public InputList<Inputs.RuleGroupRuleStatementOrStatementStatementNotStatementStatementArgs> Statements
        {
            get => _statements ?? (_statements = new InputList<Inputs.RuleGroupRuleStatementOrStatementStatementNotStatementStatementArgs>());
            set => _statements = value;
        }

        public RuleGroupRuleStatementOrStatementStatementNotStatementArgs()
        {
        }
        public static new RuleGroupRuleStatementOrStatementStatementNotStatementArgs Empty => new RuleGroupRuleStatementOrStatementStatementNotStatementArgs();
    }
}
