name: Download SDK asset
description: Restores the SDK asset for a language.

inputs:
  language:
    required: true
    description: One of nodejs, python, dotnet, go, java

runs:
  using: "composite"
  steps:
    - name: Download ${{ inputs.language }} SDK
      uses: actions/download-artifact@v4
      with:
        name: sdk.tar.gz
        path: ${{ github.workspace}}/sdk/
    - name: Uncompress SDK folder
      shell: bash
      run: tar -zxf ${{ github.workspace }}/sdk/sdk.tar.gz -C ${{ github.workspace }}/sdk
    - name: List dir
      shell: bash
      run: |
        ls ${{ github.workspace }}/sdk/python
        ls ${{ github.workspace }}/sdk/python/bin
