// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aws.AppMesh.Outputs
{

    [OutputType]
    public sealed class VirtualNodeSpecBackendDefaultsClientPolicyTls
    {
        public readonly Outputs.VirtualNodeSpecBackendDefaultsClientPolicyTlsCertificate? Certificate;
        public readonly bool? Enforce;
        public readonly ImmutableArray<int> Ports;
        public readonly Outputs.VirtualNodeSpecBackendDefaultsClientPolicyTlsValidation Validation;

        [OutputConstructor]
        private VirtualNodeSpecBackendDefaultsClientPolicyTls(
            Outputs.VirtualNodeSpecBackendDefaultsClientPolicyTlsCertificate? certificate,

            bool? enforce,

            ImmutableArray<int> ports,

            Outputs.VirtualNodeSpecBackendDefaultsClientPolicyTlsValidation validation)
        {
            Certificate = certificate;
            Enforce = enforce;
            Ports = ports;
            Validation = validation;
        }
    }
}
