// Copyright 2016-2018, Pulumi Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file contains two categories of exports:
//
//     1) A union type, InstanceType, that accepts any valid EC2 instance type.
//     2) Individual constants for each such EC2 instance type.
//
// These just give a better developer experience and are just sugared strings.

/* tslint:disable:max-line-length ordered-imports variable-name */

import { InstanceType } from ".";

export module InstanceTypes {
    /** @deprecated Use InstanceType.A1_2XLarge instead. */
    export const A1_2XLarge: InstanceType = "a1.2xlarge";
    /** @deprecated Use InstanceType.A1_4XLarge instead. */
    export const A1_4XLarge: InstanceType = "a1.4xlarge";
    /** @deprecated Use InstanceType.A1_Large instead. */
    export const A1_Large: InstanceType = "a1.large";
    /** @deprecated Use InstanceType.A1_Medium instead. */
    export const A1_Medium: InstanceType = "a1.medium";
    /** @deprecated Use InstanceType.A1_XLarge instead. */
    export const A1_XLarge: InstanceType = "a1.xlarge";
    /** @deprecated Use InstanceType.C3_2XLarge instead. */
    export const C3_2XLarge: InstanceType = "c3.2xlarge";
    /** @deprecated Use InstanceType.C3_4XLarge instead. */
    export const C3_4XLarge: InstanceType = "c3.4xlarge";
    /** @deprecated Use InstanceType.C3_8XLarge instead. */
    export const C3_8XLarge: InstanceType = "c3.8xlarge";
    /** @deprecated Use InstanceType.C3_Large instead. */
    export const C3_Large: InstanceType = "c3.large";
    /** @deprecated Use InstanceType.C3_XLarge instead. */
    export const C3_XLarge: InstanceType = "c3.xlarge";
    ///** @deprecated Use InstanceType.C4_2XLarge instead. */
    export const C4_2XLarge: InstanceType = "c4.2xlarge";
    /** @deprecated Use InstanceType.C4_4XLarge instead. */
    export const C4_4XLarge: InstanceType = "c4.4xlarge";
    /** @deprecated Use InstanceType.C4_8XLarge instead. */
    export const C4_8XLarge: InstanceType = "c4.8xlarge";
    /** @deprecated Use InstanceType.C4_Large instead. */
    export const C4_Large: InstanceType = "c4.large";
    /** @deprecated Use InstanceType.C4_XLarge instead. */
    export const C4_XLarge: InstanceType = "c4.xlarge";
    /** @deprecated Use InstanceType.C5_18XLarge instead. */
    export const C5_18XLarge: InstanceType = "c5.18xlarge";
    /** @deprecated Use InstanceType.C5_2XLarge instead. */
    export const C5_2XLarge: InstanceType = "c5.2xlarge";
    /** @deprecated Use InstanceType.C5_4XLarge instead. */
    export const C5_4XLarge: InstanceType = "c5.4xlarge";
    /** @deprecated Use InstanceType.C5_9XLarge instead. */
    export const C5_9XLarge: InstanceType = "c5.9xlarge";
    /** @deprecated Use InstanceType.C5_Large instead. */
    export const C5_Large: InstanceType = "c5.large";
    /** @deprecated Use InstanceType.C5_XLarge instead. */
    export const C5_XLarge: InstanceType = "c5.xlarge";
    /** @deprecated Use InstanceType.C5a_12XLarge instead. */
    export const C5a_12XLarge: InstanceType = "c5a.12xlarge";
    /** @deprecated Use InstanceType.C5a_16XLarge instead. */
    export const C5a_16XLarge: InstanceType = "c5a.16xlarge";
    /** @deprecated Use InstanceType.C5a_2XLarge instead. */
    export const C5a_2XLarge: InstanceType = "c5a.2xlarge";
    /** @deprecated Use InstanceType.C5a_24XLarge instead. */
    export const C5a_24XLarge: InstanceType = "c5a.24xlarge";
    /** @deprecated Use InstanceType.C5a_4XLarge instead. */
    export const C5a_4XLarge: InstanceType = "c5a.4xlarge";
    /** @deprecated Use InstanceType.C5a_8XLarge instead. */
    export const C5a_8XLarge: InstanceType = "c5a.8xlarge";
    /** @deprecated Use InstanceType.C5a_Large instead. */
    export const C5a_Large: InstanceType = "c5a.large";
    /** @deprecated Use InstanceType.C5a_XLarge instead. */
    export const C5a_XLarge: InstanceType = "c5a.xlarge";
    /** @deprecated Use InstanceType.C5d_18XLarge instead. */
    export const C5d_18XLarge: InstanceType = "c5d.18xlarge";
    /** @deprecated Use InstanceType.C5d_2XLarge instead. */
    export const C5d_2XLarge: InstanceType = "c5d.2xlarge";
    /** @deprecated Use InstanceType.C5d_4XLarge instead. */
    export const C5d_4XLarge: InstanceType = "c5d.4xlarge";
    /** @deprecated Use InstanceType.C5d_9XLarge instead. */
    export const C5d_9XLarge: InstanceType = "c5d.9xlarge";
    /** @deprecated Use InstanceType.C5d_Large instead. */
    export const C5d_Large: InstanceType = "c5d.large";
    /** @deprecated Use InstanceType.C5d_XLarge instead. */
    export const C5d_XLarge: InstanceType = "c5d.xlarge";
    /** @deprecated Use InstanceType.C5n_18XLarge instead. */
    export const C5n_18XLarge: InstanceType = "c5n.18xlarge";
    /** @deprecated Use InstanceType.C5n_2XLarge instead. */
    export const C5n_2XLarge: InstanceType = "c5n.2xlarge";
    /** @deprecated Use InstanceType.C5n_4XLarge instead. */
    export const C5n_4XLarge: InstanceType = "c5n.4xlarge";
    /** @deprecated Use InstanceType.C5n_9XLarge instead. */
    export const C5n_9XLarge: InstanceType = "c5n.9xlarge";
    /** @deprecated Use InstanceType.C5n_Large instead. */
    export const C5n_Large: InstanceType = "c5n.large";
    /** @deprecated Use InstanceType.C5n_XLarge instead. */
    export const C5n_XLarge: InstanceType = "c5n.xlarge";
    /** @deprecated Use InstanceType.D2_2XLarge instead. */
    export const D2_2XLarge: InstanceType = "d2.2xlarge";
    /** @deprecated Use InstanceType.D2_4XLarge instead. */
    export const D2_4XLarge: InstanceType = "d2.4xlarge";
    /** @deprecated Use InstanceType.D2_8XLarge instead. */
    export const D2_8XLarge: InstanceType = "d2.8xlarge";
    /** @deprecated Use InstanceType.D2_XLarge instead. */
    export const D2_XLarge: InstanceType = "d2.xlarge";
    /** @deprecated Use InstanceType.F1_16XLarge instead. */
    export const F1_16XLarge: InstanceType = "f1.16xlarge";
    /** @deprecated Use InstanceType.F1_2XLarge instead. */
    export const F1_2XLarge: InstanceType = "f1.2xlarge";
    /** @deprecated Use InstanceType.G2_2XLarge instead. */
    export const G2_2XLarge: InstanceType = "g2.2xlarge";
    /** @deprecated Use InstanceType.G2_8XLarge instead. */
    export const G2_8XLarge: InstanceType = "g2.8xlarge";
    /** @deprecated Use InstanceType.G3_16XLarge instead. */
    export const G3_16XLarge: InstanceType = "g3.16xlarge";
    /** @deprecated Use InstanceType.G3_4XLarge instead. */
    export const G3_4XLarge: InstanceType = "g3.4xlarge";
    /** @deprecated Use InstanceType.G3_8XLarge instead. */
    export const G3_8XLarge: InstanceType = "g3.8xlarge";
    /** @deprecated Use InstanceType.G3s_XLarge instead. */
    export const G3s_XLarge: InstanceType = "g3s.xlarge";
    /** @deprecated Use InstanceType.H1_16XLarge instead. */
    export const H1_16XLarge: InstanceType = "h1.16xlarge";
    /** @deprecated Use InstanceType.H1_2XLarge instead. */
    export const H1_2XLarge: InstanceType = "h1.2xlarge";
    /** @deprecated Use InstanceType.H1_4XLarge instead. */
    export const H1_4XLarge: InstanceType = "h1.4xlarge";
    /** @deprecated Use InstanceType.H1_8XLarge instead. */
    export const H1_8XLarge: InstanceType = "h1.8xlarge";
    /** @deprecated Use InstanceType.Hs1_8XLarge instead. */
    export const Hs1_8XLarge: InstanceType = "hs1.8xlarge";
    /** @deprecated Use InstanceType.I3_16XLarge instead. */
    export const I3_16XLarge: InstanceType = "i3.16xlarge";
    /** @deprecated Use InstanceType.I3_2XLarge instead. */
    export const I3_2XLarge: InstanceType = "i3.2xlarge";
    /** @deprecated Use InstanceType.I3_4XLarge instead. */
    export const I3_4XLarge: InstanceType = "i3.4xlarge";
    /** @deprecated Use InstanceType.I3_8XLarge instead. */
    export const I3_8XLarge: InstanceType = "i3.8xlarge";
    /** @deprecated Use InstanceType.I3_Large instead. */
    export const I3_Large: InstanceType = "i3.large";
    /** @deprecated Use InstanceType.I3_XLarge instead. */
    export const I3_XLarge: InstanceType = "i3.xlarge";
    /** @deprecated Use InstanceType.I3_Metal instead. */
    export const I3_Metal: InstanceType = "i3.metal";
    /** @deprecated Use InstanceType.M3_2XLarge instead. */
    export const M3_2XLarge: InstanceType = "m3.2xlarge";
    /** @deprecated Use InstanceType.M3_Large instead. */
    export const M3_Large: InstanceType = "m3.large";
    /** @deprecated Use InstanceType.M3_Medium instead. */
    export const M3_Medium: InstanceType = "m3.medium";
    /** @deprecated Use InstanceType.M3_XLarge instead. */
    export const M3_XLarge: InstanceType = "m3.xlarge";
    /** @deprecated Use InstanceType.M4_10XLarge instead. */
    export const M4_10XLarge: InstanceType = "m4.10xlarge";
    /** @deprecated Use InstanceType.M4_16XLarge instead. */
    export const M4_16XLarge: InstanceType = "m4.16xlarge";
    /** @deprecated Use InstanceType.M4_2XLarge instead. */
    export const M4_2XLarge: InstanceType = "m4.2xlarge";
    /** @deprecated Use InstanceType.M4_4XLarge instead. */
    export const M4_4XLarge: InstanceType = "m4.4xlarge";
    /** @deprecated Use InstanceType.M4_Large instead. */
    export const M4_Large: InstanceType = "m4.large";
    /** @deprecated Use InstanceType.M4_XLarge instead. */
    export const M4_XLarge: InstanceType = "m4.xlarge";
    /** @deprecated Use InstanceType.M5_Large instead. */
    export const M5_Large: InstanceType = "m5.large";
    /** @deprecated Use InstanceType.M5_XLarge instead. */
    export const M5_XLarge: InstanceType = "m5.xlarge";
    /** @deprecated Use InstanceType.M5_2XLarge instead. */
    export const M5_2XLarge: InstanceType = "m5.2xlarge";
    /** @deprecated Use InstanceType.M5_4XLarge instead. */
    export const M5_4XLarge: InstanceType = "m5.4xlarge";
    /** @deprecated Use InstanceType.M5_12XLarge instead. */
    export const M5_12XLarge: InstanceType = "m5.12xlarge";
    /** @deprecated Use InstanceType.M5_24XLarge instead. */
    export const M5_24XLarge: InstanceType = "m5.24xlarge";
    /** @deprecated Use InstanceType.M5d_Large instead. */
    export const M5d_Large: InstanceType = "m5d.large";
    /** @deprecated Use InstanceType.M5d_XLarge instead. */
    export const M5d_XLarge: InstanceType = "m5d.xlarge";
    /** @deprecated Use InstanceType.M5d_2XLarge instead. */
    export const M5d_2XLarge: InstanceType = "m5d.2xlarge";
    /** @deprecated Use InstanceType.M5d_4XLarge instead. */
    export const M5d_4XLarge: InstanceType = "m5d.4xlarge";
    /** @deprecated Use InstanceType.M5d_12XLarge instead. */
    export const M5d_12XLarge: InstanceType = "m5d.12xlarge";
    /** @deprecated Use InstanceType.M5d_24XLarge instead. */
    export const M5d_24XLarge: InstanceType = "m5d.24xlarge";
    /** @deprecated Use InstanceType.M5a_12XLarge instead. */
    export const M5a_12XLarge: InstanceType = "m5a.12xlarge";
    /** @deprecated Use InstanceType.M5a_24XLarge instead. */
    export const M5a_24XLarge: InstanceType = "m5a.24xlarge";
    /** @deprecated Use InstanceType.M5a_2XLarge instead. */
    export const M5a_2XLarge: InstanceType = "m5a.2xlarge";
    /** @deprecated Use InstanceType.M5a_4XLarge instead. */
    export const M5a_4XLarge: InstanceType = "m5a.4xlarge";
    /** @deprecated Use InstanceType.M5a_Large instead. */
    export const M5a_Large: InstanceType = "m5a.large";
    /** @deprecated Use InstanceType.M5a_XLarge instead. */
    export const M5a_XLarge: InstanceType = "m5a.xlarge";
    /** @deprecated Use InstanceType.P2_16XLarge instead. */
    export const P2_16XLarge: InstanceType = "p2.16xlarge";
    /** @deprecated Use InstanceType.P2_8XLarge instead. */
    export const P2_8XLarge: InstanceType = "p2.8xlarge";
    /** @deprecated Use InstanceType.P2_XLarge instead. */
    export const P2_XLarge: InstanceType = "p2.xlarge";
    /** @deprecated Use InstanceType.P3_16XLarge instead. */
    export const P3_16XLarge: InstanceType = "p3.16xlarge";
    /** @deprecated Use InstanceType.P3_2XLarge instead. */
    export const P3_2XLarge: InstanceType = "p3.2xlarge";
    /** @deprecated Use InstanceType.P3_8XLarge instead. */
    export const P3_8XLarge: InstanceType = "p3.8xlarge";
    /** @deprecated Use InstanceType.P3dn_24XLarge instead. */
    export const P3dn_24XLarge: InstanceType = "p3dn.24xlarge";
    /** @deprecated Use InstanceType.R3_2XLarge instead. */
    export const R3_2XLarge: InstanceType = "r3.2xlarge";
    /** @deprecated Use InstanceType.R3_4XLarge instead. */
    export const R3_4XLarge: InstanceType = "r3.4xlarge";
    /** @deprecated Use InstanceType.R3_8XLarge instead. */
    export const R3_8XLarge: InstanceType = "r3.8xlarge";
    /** @deprecated Use InstanceType.R3_Large instead. */
    export const R3_Large: InstanceType = "r3.large";
    /** @deprecated Use InstanceType.R3_XLarge instead. */
    export const R3_XLarge: InstanceType = "r3.xlarge";
    /** @deprecated Use InstanceType.R4_16XLarge instead. */
    export const R4_16XLarge: InstanceType = "r4.16xlarge";
    /** @deprecated Use InstanceType.R4_2XLarge instead. */
    export const R4_2XLarge: InstanceType = "r4.2xlarge";
    /** @deprecated Use InstanceType.R4_4XLarge instead. */
    export const R4_4XLarge: InstanceType = "r4.4xlarge";
    /** @deprecated Use InstanceType.R4_8XLarge instead. */
    export const R4_8XLarge: InstanceType = "r4.8xlarge";
    /** @deprecated Use InstanceType.R4_Large instead. */
    export const R4_Large: InstanceType = "r4.large";
    /** @deprecated Use InstanceType.R4_XLarge instead. */
    export const R4_XLarge: InstanceType = "r4.xlarge";
    /** @deprecated Use InstanceType.R5_12XLarge instead. */
    export const R5_12XLarge: InstanceType = "r5.12xlarge";
    /** @deprecated Use InstanceType.R5_24XLarge instead. */
    export const R5_24XLarge: InstanceType = "r5.24xlarge";
    /** @deprecated Use InstanceType.R5_2XLarge instead. */
    export const R5_2XLarge: InstanceType = "r5.2xlarge";
    /** @deprecated Use InstanceType.R5_4XLarge instead. */
    export const R5_4XLarge: InstanceType = "r5.4xlarge";
    /** @deprecated Use InstanceType.R5_Large instead. */
    export const R5_Large: InstanceType = "r5.large";
    /** @deprecated Use InstanceType.R5_XLarge instead. */
    export const R5_XLarge: InstanceType = "r5.xlarge";
    /** @deprecated Use InstanceType.R5a_12XLarge instead. */
    export const R5a_12XLarge: InstanceType = "r5a.12xlarge";
    /** @deprecated Use InstanceType.R5a_24XLarge instead. */
    export const R5a_24XLarge: InstanceType = "r5a.24xlarge";
    /** @deprecated Use InstanceType.R5a_2XLarge instead. */
    export const R5a_2XLarge: InstanceType = "r5a.2xlarge";
    /** @deprecated Use InstanceType.R5a_4XLarge instead. */
    export const R5a_4XLarge: InstanceType = "r5a.4xlarge";
    /** @deprecated Use InstanceType.R5a_Large instead. */
    export const R5a_Large: InstanceType = "r5a.large";
    /** @deprecated Use InstanceType.R5a_XLarge instead. */
    export const R5a_XLarge: InstanceType = "r5a.xlarge";
    /** @deprecated Use InstanceType.R5d_12XLarge instead. */
    export const R5d_12XLarge: InstanceType = "r5d.12xlarge";
    /** @deprecated Use InstanceType.R5d_24XLarge instead. */
    export const R5d_24XLarge: InstanceType = "r5d.24xlarge";
    /** @deprecated Use InstanceType.R5d_2XLarge instead. */
    export const R5d_2XLarge: InstanceType = "r5d.2xlarge";
    /** @deprecated Use InstanceType.R5d_4XLarge instead. */
    export const R5d_4XLarge: InstanceType = "r5d.4xlarge";
    /** @deprecated Use InstanceType.R5d_Large instead. */
    export const R5d_Large: InstanceType = "r5d.large";
    /** @deprecated Use InstanceType.R5d_XLarge instead. */
    export const R5d_XLarge: InstanceType = "r5d.xlarge";
    /** @deprecated Use InstanceType.T2_2XLarge instead. */
    export const T2_2XLarge: InstanceType = "t2.2xlarge";
    /** @deprecated Use InstanceType.T2_Large instead. */
    export const T2_Large: InstanceType = "t2.large";
    /** @deprecated Use InstanceType.T2_Medium instead. */
    export const T2_Medium: InstanceType = "t2.medium";
    /** @deprecated Use InstanceType.T2_Micro instead. */
    export const T2_Micro: InstanceType = "t2.micro";
    /** @deprecated Use InstanceType.T2_Nano instead. */
    export const T2_Nano: InstanceType = "t2.nano";
    /** @deprecated Use InstanceType.T2_Small instead. */
    export const T2_Small: InstanceType = "t2.small";
    /** @deprecated Use InstanceType.T2_XLarge instead. */
    export const T2_XLarge: InstanceType = "t2.xlarge";
    /** @deprecated Use InstanceType.T3_2XLarge instead. */
    export const T3_2XLarge: InstanceType = "t3.2xlarge";
    /** @deprecated Use InstanceType.T3_Large instead. */
    export const T3_Large: InstanceType = "t3.large";
    /** @deprecated Use InstanceType.T3_Medium instead. */
    export const T3_Medium: InstanceType = "t3.medium";
    /** @deprecated Use InstanceType.T3_Micro instead. */
    export const T3_Micro: InstanceType = "t3.micro";
    /** @deprecated Use InstanceType.T3_Nano instead. */
    export const T3_Nano: InstanceType = "t3.nano";
    /** @deprecated Use InstanceType.T3_Small instead. */
    export const T3_Small: InstanceType = "t3.small";
    /** @deprecated Use InstanceType.T3_XLarge instead. */
    export const T3_XLarge: InstanceType = "t3.xlarge";
    /** @deprecated Use InstanceType.T3a_2XLarge instead. */
    export const T3a_2XLarge: InstanceType = "t3a.2xlarge";
    /** @deprecated Use InstanceType.T3a_Large instead. */
    export const T3a_Large: InstanceType = "t3a.large";
    /** @deprecated Use InstanceType.T3a_Medium instead. */
    export const T3a_Medium: InstanceType = "t3a.medium";
    /** @deprecated Use InstanceType.T3a_Micro instead. */
    export const T3a_Micro: InstanceType = "t3a.micro";
    /** @deprecated Use InstanceType.T3a_Nano instead. */
    export const T3a_Nano: InstanceType = "t3a.nano";
    /** @deprecated Use InstanceType.T3a_Small instead. */
    export const T3a_Small: InstanceType = "t3a.small";
    /** @deprecated Use InstanceType.T3a_XLarge instead. */
    export const T3a_XLarge: InstanceType = "t3a.xlarge";
    /** @deprecated Use InstanceType.U_12tb1Metal instead. */
    export const U_12tb1Metal: InstanceType = "u-12tb1.metal";
    /** @deprecated Use InstanceType.U_6tb1Metal instead. */
    export const U_6tb1Metal: InstanceType = "u-6tb1.metal";
    /** @deprecated Use InstanceType.U_9tb1Metal instead. */
    export const U_9tb1Metal: InstanceType = "u-9tb1.metal";
    /** @deprecated Use InstanceType.X1_16XLarge instead. */
    export const X1_16XLarge: InstanceType = "x1.16xlarge";
    /** @deprecated Use InstanceType.X1_32XLarge instead. */
    export const X1_32XLarge: InstanceType = "x1.32xlarge";
    /** @deprecated Use InstanceType.X1e_16XLarge instead. */
    export const X1e_16XLarge: InstanceType = "x1e.16xlarge";
    /** @deprecated Use InstanceType.X1e_2XLarge instead. */
    export const X1e_2XLarge: InstanceType = "x1e.2xlarge";
    /** @deprecated Use InstanceType.X1e_32XLarge instead. */
    export const X1e_32XLarge: InstanceType = "x1e.32xlarge";
    /** @deprecated Use InstanceType.X1e_4XLarge instead. */
    export const X1e_4XLarge: InstanceType = "x1e.4xlarge";
    /** @deprecated Use InstanceType.X1e_8XLarge instead. */
    export const X1e_8XLarge: InstanceType = "x1e.8xlarge";
    /** @deprecated Use InstanceType.X1e_XLarge instead. */
    export const X1e_XLarge: InstanceType = "x1e.xlarge";
    /** @deprecated Use InstanceType.Z1d_12XLarge instead. */
    export const Z1d_12XLarge: InstanceType = "z1d.12xlarge";
    /** @deprecated Use InstanceType.Z1d_2XLarge instead. */
    export const Z1d_2XLarge: InstanceType = "z1d.2xlarge";
    /** @deprecated Use InstanceType.Z1d_3XLarge instead. */
    export const Z1d_3XLarge: InstanceType = "z1d.3xlarge";
    /** @deprecated Use InstanceType.Z1d_6XLarge instead. */
    export const Z1d_6XLarge: InstanceType = "z1d.6xlarge";
    /** @deprecated Use InstanceType.Z1d_Large instead. */
    export const Z1d_Large: InstanceType = "z1d.large";
    /** @deprecated Use InstanceType.Z1d_XLarge instead. */
    export const Z1d_XLarge: InstanceType = "z1d.xlarge";
}
