// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aws.CloudTrail.Inputs
{

    public sealed class TrailEventSelectorArgs : global::Pulumi.ResourceArgs
    {
        [Input("dataResources")]
        private InputList<Inputs.TrailEventSelectorDataResourceArgs>? _dataResources;
        public InputList<Inputs.TrailEventSelectorDataResourceArgs> DataResources
        {
            get => _dataResources ?? (_dataResources = new InputList<Inputs.TrailEventSelectorDataResourceArgs>());
            set => _dataResources = value;
        }

        [Input("excludeManagementEventSources")]
        private InputList<string>? _excludeManagementEventSources;
        public InputList<string> ExcludeManagementEventSources
        {
            get => _excludeManagementEventSources ?? (_excludeManagementEventSources = new InputList<string>());
            set => _excludeManagementEventSources = value;
        }

        [Input("includeManagementEvents")]
        public Input<bool>? IncludeManagementEvents { get; set; }

        [Input("readWriteType")]
        public Input<string>? ReadWriteType { get; set; }

        public TrailEventSelectorArgs()
        {
        }
        public static new TrailEventSelectorArgs Empty => new TrailEventSelectorArgs();
    }
}
