name: Upload SDK asset
description: Upload the SDK for a specific language as an asset for the workflow.

inputs:
  language:
    required: true
    description: One of nodejs, python, dotnet, go, java

runs:
  using: "composite"
  steps:
    - name: Compress SDK folder
      shell: bash
      run: tar -zcf sdk/${{ inputs.language }}.tar.gz -C sdk/${{ inputs.language }} .
    - name: Upload artifacts
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: ${{ inputs.language  }}-sdk.tar.gz
        path: ${{ github.workspace}}/sdk/${{ inputs.language }}.tar.gz
        retention-days: 30
