// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.policypacks.aws.s3control;

import com.pulumi.policypacks.aws.s3control.ObjectLambdaAccessPointConfigurationTransformationConfigurationContentTransformationAwsLambda;


public final class ObjectLambdaAccessPointConfigurationTransformationConfigurationContentTransformation {

    /**
     * Configuration for an AWS Lambda function. See AWS Lambda below for more details.
     * 
     */
    public ObjectLambdaAccessPointConfigurationTransformationConfigurationContentTransformationAwsLambda awsLambda;



}
