// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aws.networkfirewall.outputs;

import com.pulumi.aws.networkfirewall.outputs.VpcEndpointAssociationVpcEndpointAssociationStatusAssociationSyncStateAttachment;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class VpcEndpointAssociationVpcEndpointAssociationStatusAssociationSyncState {
    /**
     * @return Nested list describing the attachment status of the firewall&#39;s VPC Endpoint Association with a single VPC subnet.
     * 
     */
    private List<VpcEndpointAssociationVpcEndpointAssociationStatusAssociationSyncStateAttachment> attachments;
    /**
     * @return The Availability Zone where the subnet is configured.
     * 
     */
    private String availabilityZone;

    private VpcEndpointAssociationVpcEndpointAssociationStatusAssociationSyncState() {}
    /**
     * @return Nested list describing the attachment status of the firewall&#39;s VPC Endpoint Association with a single VPC subnet.
     * 
     */
    public List<VpcEndpointAssociationVpcEndpointAssociationStatusAssociationSyncStateAttachment> attachments() {
        return this.attachments;
    }
    /**
     * @return The Availability Zone where the subnet is configured.
     * 
     */
    public String availabilityZone() {
        return this.availabilityZone;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(VpcEndpointAssociationVpcEndpointAssociationStatusAssociationSyncState defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<VpcEndpointAssociationVpcEndpointAssociationStatusAssociationSyncStateAttachment> attachments;
        private String availabilityZone;
        public Builder() {}
        public Builder(VpcEndpointAssociationVpcEndpointAssociationStatusAssociationSyncState defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.attachments = defaults.attachments;
    	      this.availabilityZone = defaults.availabilityZone;
        }

        @CustomType.Setter
        public Builder attachments(List<VpcEndpointAssociationVpcEndpointAssociationStatusAssociationSyncStateAttachment> attachments) {
            if (attachments == null) {
              throw new MissingRequiredPropertyException("VpcEndpointAssociationVpcEndpointAssociationStatusAssociationSyncState", "attachments");
            }
            this.attachments = attachments;
            return this;
        }
        public Builder attachments(VpcEndpointAssociationVpcEndpointAssociationStatusAssociationSyncStateAttachment... attachments) {
            return attachments(List.of(attachments));
        }
        @CustomType.Setter
        public Builder availabilityZone(String availabilityZone) {
            if (availabilityZone == null) {
              throw new MissingRequiredPropertyException("VpcEndpointAssociationVpcEndpointAssociationStatusAssociationSyncState", "availabilityZone");
            }
            this.availabilityZone = availabilityZone;
            return this;
        }
        public VpcEndpointAssociationVpcEndpointAssociationStatusAssociationSyncState build() {
            final var _resultValue = new VpcEndpointAssociationVpcEndpointAssociationStatusAssociationSyncState();
            _resultValue.attachments = attachments;
            _resultValue.availabilityZone = availabilityZone;
            return _resultValue;
        }
    }
}
