// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aws.S3.Inputs
{

    public sealed class BucketServerSideEncryptionConfigurationV2RuleApplyServerSideEncryptionByDefaultArgs : global::Pulumi.ResourceArgs
    {
        [Input("kmsMasterKeyId")]
        public Input<string>? KmsMasterKeyId { get; set; }

        [Input("sseAlgorithm", required: true)]
        public Input<string> SseAlgorithm { get; set; } = null!;

        public BucketServerSideEncryptionConfigurationV2RuleApplyServerSideEncryptionByDefaultArgs()
        {
        }
        public static new BucketServerSideEncryptionConfigurationV2RuleApplyServerSideEncryptionByDefaultArgs Empty => new BucketServerSideEncryptionConfigurationV2RuleApplyServerSideEncryptionByDefaultArgs();
    }
}
