// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.policypacks.aws.s3.outputs;

import com.pulumi.core.UndeferrableValueException;
import com.pulumi.core.annotations.PolicyResourceProperty;
import com.pulumi.policypacks.aws.s3.outputs.BucketLoggingV2TargetGrantGrantee;
import java.lang.String;


public final class BucketLoggingV2TargetGrant {

    /**
     * Configuration block for the person being granted permissions. See below.
     * 
     */
    @PolicyResourceProperty(name="grantee", flag="unknown_grantee")
    private BucketLoggingV2TargetGrantGrantee value_grantee;
    private boolean unknown_grantee;
    public BucketLoggingV2TargetGrantGrantee grantee() {
        if (!unknown_grantee) return value_grantee;
        throw new UndeferrableValueException("Value 'BucketLoggingV2TargetGrant.grantee' is not present");
    }

    /**
     * Logging permissions assigned to the grantee for the bucket. Valid values: `FULL_CONTROL`, `READ`, `WRITE`.
     * 
     */
    @PolicyResourceProperty(name="permission", flag="unknown_permission")
    private String value_permission;
    private boolean unknown_permission;
    public String permission() {
        if (!unknown_permission) return value_permission;
        throw new UndeferrableValueException("Value 'BucketLoggingV2TargetGrant.permission' is not present");
    }

}
