// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.PolicyPacks.Aws.AppMesh.Outputs
{
    public sealed class GetGatewayRouteSpecHttpRouteMatchQueryParameterResult
    {
        [Input("matches")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<List<Outputs.GetGatewayRouteSpecHttpRouteMatchQueryParameterMatchResult>> _mMatches;

        public List<Outputs.GetGatewayRouteSpecHttpRouteMatchQueryParameterMatchResult>? Matches => _mMatches.GetValue("matches");

        /// <summary>
        /// Name of the gateway route.
        /// </summary>
        [Input("name")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<string> _mName;

        public string? Name => _mName.GetValue("name");
    }
}
