// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.PolicyPacks.Aws.Sagemaker
{
    [PolicyResourceType("aws:sagemaker/space:Space")]
    public sealed class Space : global::Pulumi.PolicyResource
    {
        /// <summary>
        /// The space's Amazon Resource Name (ARN).
        /// </summary>
        [Input("arn")]
        public string? Arn;

        /// <summary>
        /// The ID of the associated Domain.
        /// </summary>
        [Input("domainId")]
        public string? DomainId;

        /// <summary>
        /// The ID of the space's profile in the Amazon Elastic File System volume.
        /// </summary>
        [Input("homeEfsFileSystemUid")]
        public string? HomeEfsFileSystemUid;

        /// <summary>
        /// A collection of ownership settings. Required if `space_sharing_settings` is set. See `ownership_settings` Block below.
        /// </summary>
        [Input("ownershipSettings")]
        public SpaceOwnershipSettings? OwnershipSettings;

        /// <summary>
        /// The name of the space that appears in the SageMaker AI Studio UI.
        /// </summary>
        [Input("spaceDisplayName")]
        public string? SpaceDisplayName;

        /// <summary>
        /// The name of the space.
        /// </summary>
        [Input("spaceName")]
        public string? SpaceName;

        /// <summary>
        /// A collection of space settings. See `space_settings` Block below.
        /// </summary>
        [Input("spaceSettings")]
        public SpaceSpaceSettings? SpaceSettings;

        /// <summary>
        /// A collection of space sharing settings. Required if `ownership_settings` is set. See `space_sharing_settings` Block below.
        /// </summary>
        [Input("spaceSharingSettings")]
        public SpaceSpaceSharingSettings? SpaceSharingSettings;

        /// <summary>
        /// A map of tags to assign to the resource. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
        /// </summary>
        [Input("tags")]
        public Dictionary<string, string>? Tags;

        /// <summary>
        /// A map of tags assigned to the resource, including those inherited from the provider `default_tags` configuration block.
        /// </summary>
        [Input("tagsAll")]
        public Dictionary<string, string>? TagsAll;

        /// <summary>
        /// Returns the URL of the space. If the space is created with Amazon Web Services IAM Identity Center (Successor to Amazon Web Services Single Sign-On) authentication, users can navigate to the URL after appending the respective redirect parameter for the application type to be federated through Amazon Web Services IAM Identity Center.
        /// </summary>
        [Input("url")]
        public string? Url;
    }
}
