// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.policypacks.aws.wafv2.inputs;

import com.pulumi.core.UndeferrableValue;
import com.pulumi.policypacks.aws.wafv2.inputs.WebAclRuleStatementRuleGroupReferenceStatementRuleActionOverrideActionToUseCountCustomRequestHandlingArgs;
import javax.annotation.Nullable;


public final class WebAclRuleStatementRuleGroupReferenceStatementRuleActionOverrideActionToUseCountArgs {

    /**
     * Defines custom handling for the web request. See `custom_request_handling` below for details.
     * 
     */
    private UndeferrableValue<WebAclRuleStatementRuleGroupReferenceStatementRuleActionOverrideActionToUseCountCustomRequestHandlingArgs> customRequestHandling;

    public WebAclRuleStatementRuleGroupReferenceStatementRuleActionOverrideActionToUseCountCustomRequestHandlingArgs customRequestHandling() {
        if (customRequestHandling == null) return null;
        return customRequestHandling.getValue("WebAclRuleStatementRuleGroupReferenceStatementRuleActionOverrideActionToUseCountArgs.customRequestHandling");
    }

}
