// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aws.Synthetics.Inputs
{

    public sealed class CanaryScheduleArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Duration in seconds, for the canary to continue making regular runs according to the schedule in the Expression value.
        /// </summary>
        [Input("durationInSeconds")]
        public Input<int>? DurationInSeconds { get; set; }

        /// <summary>
        /// Rate expression that defines how often the canary is to run. The syntax is rate(number unit). unit can be minute, minutes, or hour.
        /// </summary>
        [Input("expression", required: true)]
        public Input<string> Expression { get; set; } = null!;

        public CanaryScheduleArgs()
        {
        }
    }
}
