// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aws.ec2transitgateway.inputs;

import com.pulumi.aws.ec2transitgateway.inputs.GetTransitGatewayFilter;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetTransitGatewayPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetTransitGatewayPlainArgs Empty = new GetTransitGatewayPlainArgs();

    @Import(name="filters")
    private @Nullable List<GetTransitGatewayFilter> filters;

    public Optional<List<GetTransitGatewayFilter>> filters() {
        return Optional.ofNullable(this.filters);
    }

    @Import(name="id")
    private @Nullable String id;

    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    @Import(name="region")
    private @Nullable String region;

    public Optional<String> region() {
        return Optional.ofNullable(this.region);
    }

    @Import(name="tags")
    private @Nullable Map<String,String> tags;

    public Optional<Map<String,String>> tags() {
        return Optional.ofNullable(this.tags);
    }

    private GetTransitGatewayPlainArgs() {}

    private GetTransitGatewayPlainArgs(GetTransitGatewayPlainArgs $) {
        this.filters = $.filters;
        this.id = $.id;
        this.region = $.region;
        this.tags = $.tags;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetTransitGatewayPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetTransitGatewayPlainArgs $;

        public Builder() {
            $ = new GetTransitGatewayPlainArgs();
        }

        public Builder(GetTransitGatewayPlainArgs defaults) {
            $ = new GetTransitGatewayPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder filters(@Nullable List<GetTransitGatewayFilter> filters) {
            $.filters = filters;
            return this;
        }

        public Builder filters(GetTransitGatewayFilter... filters) {
            return filters(List.of(filters));
        }

        public Builder id(@Nullable String id) {
            $.id = id;
            return this;
        }

        public Builder region(@Nullable String region) {
            $.region = region;
            return this;
        }

        public Builder tags(@Nullable Map<String,String> tags) {
            $.tags = tags;
            return this;
        }

        public GetTransitGatewayPlainArgs build() {
            return $;
        }
    }

}
