// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.policypacks.aws.medialive.outputs;

import com.pulumi.core.UndeferrableValue;
import com.pulumi.policypacks.aws.medialive.outputs.ChannelEncoderSettingsOutputGroupOutputGroupSettingsArchiveGroupSetting;
import com.pulumi.policypacks.aws.medialive.outputs.ChannelEncoderSettingsOutputGroupOutputGroupSettingsFrameCaptureGroupSettings;
import com.pulumi.policypacks.aws.medialive.outputs.ChannelEncoderSettingsOutputGroupOutputGroupSettingsHlsGroupSettings;
import com.pulumi.policypacks.aws.medialive.outputs.ChannelEncoderSettingsOutputGroupOutputGroupSettingsMediaPackageGroupSettings;
import com.pulumi.policypacks.aws.medialive.outputs.ChannelEncoderSettingsOutputGroupOutputGroupSettingsMsSmoothGroupSettings;
import com.pulumi.policypacks.aws.medialive.outputs.ChannelEncoderSettingsOutputGroupOutputGroupSettingsMultiplexGroupSettings;
import com.pulumi.policypacks.aws.medialive.outputs.ChannelEncoderSettingsOutputGroupOutputGroupSettingsRtmpGroupSettings;
import com.pulumi.policypacks.aws.medialive.outputs.ChannelEncoderSettingsOutputGroupOutputGroupSettingsUdpGroupSettings;
import java.util.List;
import javax.annotation.Nullable;


public final class ChannelEncoderSettingsOutputGroupOutputGroupSettings {

    /**
     * Archive group settings. See Archive Group Settings for more details.
     * 
     */
    private @Nullable UndeferrableValue<List<ChannelEncoderSettingsOutputGroupOutputGroupSettingsArchiveGroupSetting>> archiveGroupSettings;

    public @Nullable List<ChannelEncoderSettingsOutputGroupOutputGroupSettingsArchiveGroupSetting> archiveGroupSettings() {
        if (archiveGroupSettings == null) return null;
        return archiveGroupSettings.getValue("ChannelEncoderSettingsOutputGroupOutputGroupSettings.archiveGroupSettings");
    }

    private @Nullable UndeferrableValue<ChannelEncoderSettingsOutputGroupOutputGroupSettingsFrameCaptureGroupSettings> frameCaptureGroupSettings;

    public @Nullable ChannelEncoderSettingsOutputGroupOutputGroupSettingsFrameCaptureGroupSettings frameCaptureGroupSettings() {
        if (frameCaptureGroupSettings == null) return null;
        return frameCaptureGroupSettings.getValue("ChannelEncoderSettingsOutputGroupOutputGroupSettings.frameCaptureGroupSettings");
    }

    private @Nullable UndeferrableValue<ChannelEncoderSettingsOutputGroupOutputGroupSettingsHlsGroupSettings> hlsGroupSettings;

    public @Nullable ChannelEncoderSettingsOutputGroupOutputGroupSettingsHlsGroupSettings hlsGroupSettings() {
        if (hlsGroupSettings == null) return null;
        return hlsGroupSettings.getValue("ChannelEncoderSettingsOutputGroupOutputGroupSettings.hlsGroupSettings");
    }

    /**
     * Media package group settings. See Media Package Group Settings for more details.
     * 
     */
    private @Nullable UndeferrableValue<ChannelEncoderSettingsOutputGroupOutputGroupSettingsMediaPackageGroupSettings> mediaPackageGroupSettings;

    public @Nullable ChannelEncoderSettingsOutputGroupOutputGroupSettingsMediaPackageGroupSettings mediaPackageGroupSettings() {
        if (mediaPackageGroupSettings == null) return null;
        return mediaPackageGroupSettings.getValue("ChannelEncoderSettingsOutputGroupOutputGroupSettings.mediaPackageGroupSettings");
    }

    private @Nullable UndeferrableValue<ChannelEncoderSettingsOutputGroupOutputGroupSettingsMsSmoothGroupSettings> msSmoothGroupSettings;

    public @Nullable ChannelEncoderSettingsOutputGroupOutputGroupSettingsMsSmoothGroupSettings msSmoothGroupSettings() {
        if (msSmoothGroupSettings == null) return null;
        return msSmoothGroupSettings.getValue("ChannelEncoderSettingsOutputGroupOutputGroupSettings.msSmoothGroupSettings");
    }

    private @Nullable UndeferrableValue<ChannelEncoderSettingsOutputGroupOutputGroupSettingsMultiplexGroupSettings> multiplexGroupSettings;

    public @Nullable ChannelEncoderSettingsOutputGroupOutputGroupSettingsMultiplexGroupSettings multiplexGroupSettings() {
        if (multiplexGroupSettings == null) return null;
        return multiplexGroupSettings.getValue("ChannelEncoderSettingsOutputGroupOutputGroupSettings.multiplexGroupSettings");
    }

    /**
     * RTMP group settings. See RTMP Group Settings for more details.
     * 
     */
    private @Nullable UndeferrableValue<ChannelEncoderSettingsOutputGroupOutputGroupSettingsRtmpGroupSettings> rtmpGroupSettings;

    public @Nullable ChannelEncoderSettingsOutputGroupOutputGroupSettingsRtmpGroupSettings rtmpGroupSettings() {
        if (rtmpGroupSettings == null) return null;
        return rtmpGroupSettings.getValue("ChannelEncoderSettingsOutputGroupOutputGroupSettings.rtmpGroupSettings");
    }

    private @Nullable UndeferrableValue<ChannelEncoderSettingsOutputGroupOutputGroupSettingsUdpGroupSettings> udpGroupSettings;

    public @Nullable ChannelEncoderSettingsOutputGroupOutputGroupSettingsUdpGroupSettings udpGroupSettings() {
        if (udpGroupSettings == null) return null;
        return udpGroupSettings.getValue("ChannelEncoderSettingsOutputGroupOutputGroupSettings.udpGroupSettings");
    }

}
