// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package budgets

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-aws/sdk/v6/go/aws/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

// Data source for managing an AWS Web Services Budgets Budget.
func LookupBudget(ctx *pulumi.Context, args *LookupBudgetArgs, opts ...pulumi.InvokeOption) (*LookupBudgetResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupBudgetResult
	err := ctx.Invoke("aws:budgets/getBudget:getBudget", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getBudget.
type LookupBudgetArgs struct {
	// The ID of the target account for budget. Will use current user's accountId by default if omitted.
	AccountId *string `pulumi:"accountId"`
	// The name of a budget. Unique within accounts.
	//
	// The following arguments are optional:
	Name string `pulumi:"name"`
	// The prefix of the name of a budget. Unique within accounts.
	NamePrefix *string `pulumi:"namePrefix"`
}

// A collection of values returned by getBudget.
type LookupBudgetResult struct {
	AccountId string `pulumi:"accountId"`
	Arn       string `pulumi:"arn"`
	// Object containing [AutoAdjustData] which determines the budget amount for an auto-adjusting budget.
	AutoAdjustDatas []GetBudgetAutoAdjustData `pulumi:"autoAdjustDatas"`
	// Boolean indicating whether this budget has been exceeded.
	BudgetExceeded bool `pulumi:"budgetExceeded"`
	// The total amount of cost, usage, RI utilization, RI coverage, Savings Plans utilization, or Savings Plans coverage that you want to track with your budget. Contains object Spend.
	BudgetLimits []GetBudgetBudgetLimit `pulumi:"budgetLimits"`
	// Whether this budget tracks monetary cost or usage.
	BudgetType string `pulumi:"budgetType"`
	// The spend objects that are associated with this budget. The actualSpend tracks how much you've used, cost, usage, RI units, or Savings Plans units and the forecastedSpend tracks how much that you're predicted to spend based on your historical usage profile.
	CalculatedSpends []GetBudgetCalculatedSpend `pulumi:"calculatedSpends"`
	// A list of CostFilter name/values pair to apply to budget.
	CostFilters []GetBudgetCostFilter `pulumi:"costFilters"`
	// Object containing CostTypes The types of cost included in a budget, such as tax and subscriptions.
	CostTypes []GetBudgetCostType `pulumi:"costTypes"`
	// The provider-assigned unique ID for this managed resource.
	Id         string  `pulumi:"id"`
	Name       string  `pulumi:"name"`
	NamePrefix *string `pulumi:"namePrefix"`
	// Object containing Budget Notifications. Can be used multiple times to define more than one budget notification.
	Notifications []GetBudgetNotification `pulumi:"notifications"`
	// Object containing Planned Budget Limits. Can be used multiple times to plan more than one budget limit. See [PlannedBudgetLimits](https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_budgets_Budget.html#awscostmanagement-Type-budgets_Budget-PlannedBudgetLimits) documentation.
	PlannedLimits []GetBudgetPlannedLimit `pulumi:"plannedLimits"`
	// The end of the time period covered by the budget. There are no restrictions on the end date. Format: `2017-01-01_12:00`.
	TimePeriodEnd string `pulumi:"timePeriodEnd"`
	// The start of the time period covered by the budget. If you don't specify a start date, AWS defaults to the start of your chosen time period. The start date must come before the end date. Format: `2017-01-01_12:00`.
	TimePeriodStart string `pulumi:"timePeriodStart"`
	// The length of time until a budget resets the actual and forecasted spend. Valid values: `MONTHLY`, `QUARTERLY`, `ANNUALLY`, and `DAILY`.
	TimeUnit string `pulumi:"timeUnit"`
}

func LookupBudgetOutput(ctx *pulumi.Context, args LookupBudgetOutputArgs, opts ...pulumi.InvokeOption) LookupBudgetResultOutput {
	outputResult := pulumix.ApplyErr[*LookupBudgetArgs](args.ToOutput(), func(plainArgs *LookupBudgetArgs) (*LookupBudgetResult, error) {
		return LookupBudget(ctx, plainArgs, opts...)
	})

	return pulumix.Cast[LookupBudgetResultOutput, *LookupBudgetResult](outputResult)
}

// A collection of arguments for invoking getBudget.
type LookupBudgetOutputArgs struct {
	// The ID of the target account for budget. Will use current user's accountId by default if omitted.
	AccountId pulumix.Input[*string] `pulumi:"accountId"`
	// The name of a budget. Unique within accounts.
	//
	// The following arguments are optional:
	Name pulumix.Input[string] `pulumi:"name"`
	// The prefix of the name of a budget. Unique within accounts.
	NamePrefix pulumix.Input[*string] `pulumi:"namePrefix"`
}

func (args LookupBudgetOutputArgs) ToOutput() pulumix.Output[*LookupBudgetArgs] {
	allArgs := pulumix.All(
		args.AccountId.ToOutput(context.Background()).AsAny(),
		args.Name.ToOutput(context.Background()).AsAny(),
		args.NamePrefix.ToOutput(context.Background()).AsAny())
	return pulumix.Apply[[]any](allArgs, func(resolvedArgs []interface{}) *LookupBudgetArgs {
		return &LookupBudgetArgs{
			AccountId:  resolvedArgs[0].(*string),
			Name:       resolvedArgs[1].(string),
			NamePrefix: resolvedArgs[2].(*string),
		}
	})
}

type LookupBudgetResultOutput struct{ *pulumi.OutputState }

func (LookupBudgetResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupBudgetResult)(nil)).Elem()
}

func (o LookupBudgetResultOutput) ToOutput(context.Context) pulumix.Output[*LookupBudgetResult] {
	return pulumix.Output[*LookupBudgetResult]{
		OutputState: o.OutputState,
	}
}

func (o LookupBudgetResultOutput) AccountId() pulumix.Output[string] {
	return pulumix.Apply[*LookupBudgetResult](o, func(v *LookupBudgetResult) string { return v.AccountId })
}

func (o LookupBudgetResultOutput) Arn() pulumix.Output[string] {
	return pulumix.Apply[*LookupBudgetResult](o, func(v *LookupBudgetResult) string { return v.Arn })
}

func (o LookupBudgetResultOutput) AutoAdjustDatas() pulumix.GArrayOutput[GetBudgetAutoAdjustData, GetBudgetAutoAdjustDataOutput] {
	value := pulumix.Apply[*LookupBudgetResult](o, func(v *LookupBudgetResult) []GetBudgetAutoAdjustData { return v.AutoAdjustDatas })
	return pulumix.GArrayOutput[GetBudgetAutoAdjustData, GetBudgetAutoAdjustDataOutput]{
		OutputState: value.OutputState,
	}
}

func (o LookupBudgetResultOutput) BudgetExceeded() pulumix.Output[bool] {
	return pulumix.Apply[*LookupBudgetResult](o, func(v *LookupBudgetResult) bool { return v.BudgetExceeded })
}

func (o LookupBudgetResultOutput) BudgetLimits() pulumix.GArrayOutput[GetBudgetBudgetLimit, GetBudgetBudgetLimitOutput] {
	value := pulumix.Apply[*LookupBudgetResult](o, func(v *LookupBudgetResult) []GetBudgetBudgetLimit { return v.BudgetLimits })
	return pulumix.GArrayOutput[GetBudgetBudgetLimit, GetBudgetBudgetLimitOutput]{
		OutputState: value.OutputState,
	}
}

func (o LookupBudgetResultOutput) BudgetType() pulumix.Output[string] {
	return pulumix.Apply[*LookupBudgetResult](o, func(v *LookupBudgetResult) string { return v.BudgetType })
}

func (o LookupBudgetResultOutput) CalculatedSpends() pulumix.GArrayOutput[GetBudgetCalculatedSpend, GetBudgetCalculatedSpendOutput] {
	value := pulumix.Apply[*LookupBudgetResult](o, func(v *LookupBudgetResult) []GetBudgetCalculatedSpend { return v.CalculatedSpends })
	return pulumix.GArrayOutput[GetBudgetCalculatedSpend, GetBudgetCalculatedSpendOutput]{
		OutputState: value.OutputState,
	}
}

func (o LookupBudgetResultOutput) CostFilters() pulumix.GArrayOutput[GetBudgetCostFilter, GetBudgetCostFilterOutput] {
	value := pulumix.Apply[*LookupBudgetResult](o, func(v *LookupBudgetResult) []GetBudgetCostFilter { return v.CostFilters })
	return pulumix.GArrayOutput[GetBudgetCostFilter, GetBudgetCostFilterOutput]{
		OutputState: value.OutputState,
	}
}

func (o LookupBudgetResultOutput) CostTypes() pulumix.GArrayOutput[GetBudgetCostType, GetBudgetCostTypeOutput] {
	value := pulumix.Apply[*LookupBudgetResult](o, func(v *LookupBudgetResult) []GetBudgetCostType { return v.CostTypes })
	return pulumix.GArrayOutput[GetBudgetCostType, GetBudgetCostTypeOutput]{
		OutputState: value.OutputState,
	}
}

func (o LookupBudgetResultOutput) Id() pulumix.Output[string] {
	return pulumix.Apply[*LookupBudgetResult](o, func(v *LookupBudgetResult) string { return v.Id })
}

func (o LookupBudgetResultOutput) Name() pulumix.Output[string] {
	return pulumix.Apply[*LookupBudgetResult](o, func(v *LookupBudgetResult) string { return v.Name })
}

func (o LookupBudgetResultOutput) NamePrefix() pulumix.Output[*string] {
	return pulumix.Apply[*LookupBudgetResult](o, func(v *LookupBudgetResult) *string { return v.NamePrefix })
}

func (o LookupBudgetResultOutput) Notifications() pulumix.GArrayOutput[GetBudgetNotification, GetBudgetNotificationOutput] {
	value := pulumix.Apply[*LookupBudgetResult](o, func(v *LookupBudgetResult) []GetBudgetNotification { return v.Notifications })
	return pulumix.GArrayOutput[GetBudgetNotification, GetBudgetNotificationOutput]{
		OutputState: value.OutputState,
	}
}

func (o LookupBudgetResultOutput) PlannedLimits() pulumix.GArrayOutput[GetBudgetPlannedLimit, GetBudgetPlannedLimitOutput] {
	value := pulumix.Apply[*LookupBudgetResult](o, func(v *LookupBudgetResult) []GetBudgetPlannedLimit { return v.PlannedLimits })
	return pulumix.GArrayOutput[GetBudgetPlannedLimit, GetBudgetPlannedLimitOutput]{
		OutputState: value.OutputState,
	}
}

func (o LookupBudgetResultOutput) TimePeriodEnd() pulumix.Output[string] {
	return pulumix.Apply[*LookupBudgetResult](o, func(v *LookupBudgetResult) string { return v.TimePeriodEnd })
}

func (o LookupBudgetResultOutput) TimePeriodStart() pulumix.Output[string] {
	return pulumix.Apply[*LookupBudgetResult](o, func(v *LookupBudgetResult) string { return v.TimePeriodStart })
}

func (o LookupBudgetResultOutput) TimeUnit() pulumix.Output[string] {
	return pulumix.Apply[*LookupBudgetResult](o, func(v *LookupBudgetResult) string { return v.TimeUnit })
}
