// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.policypacks.aws.s3tables.inputs;

import com.pulumi.core.UndeferrableValue;
import com.pulumi.policypacks.aws.s3tables.inputs.TableBucketMaintenanceConfigurationIcebergUnreferencedFileRemovalArgs;


public final class TableBucketMaintenanceConfigurationArgs {

    /**
     * A single Iceberg unreferenced file removal settings object.
     * See `iceberg_unreferenced_file_removal` below.
     * 
     */
    private UndeferrableValue<TableBucketMaintenanceConfigurationIcebergUnreferencedFileRemovalArgs> icebergUnreferencedFileRemoval;

    public TableBucketMaintenanceConfigurationIcebergUnreferencedFileRemovalArgs icebergUnreferencedFileRemoval() {
        if (icebergUnreferencedFileRemoval == null) return null;
        return icebergUnreferencedFileRemoval.getValue("TableBucketMaintenanceConfigurationArgs.icebergUnreferencedFileRemoval");
    }

}
