name: Setup tools
description: Installs Go, Pulumi, pulumictl, schema-tools, Node.JS, Python, dotnet and Java.

inputs:
  tools:
    description: |
      Comma separated list of tools to install. The default of "all" installs all tools. Available tools are:
        go
        pulumicli
        pulumictl
        schema-tools
        nodejs
        python
        dotnet
        java
    default: all
  cache-go:
    description: |
      Whether to enable the GitHub cache for Go. Appropriate for disabling in
      smaller jobs that typically completely before the "real" job has an
      opportunity to populate the cache.
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Install Go
      if: inputs.tools == 'all' || contains(inputs.tools, 'go')
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
      with:
        go-version: "1.23.x"
        cache-dependency-path: |
          provider/*.sum
          upstream/*.sum
          sdk/go/*.sum
          sdk/*.sum
          *.sum
        # TODO(https://github.com/actions/setup-go/issues/316): Restore but don't save the cache.
        cache: ${{ inputs.cache-go }}

    - name: Install pulumictl
      if: inputs.tools == 'all' || contains(inputs.tools, 'pulumictl')
      uses: jaxxstorm/action-install-gh-release@cd6b2b78ad38bdd294341cda064ec0692b06215b # v1.14.0
      with:
        tag: v0.0.46
        repo: pulumi/pulumictl

    - name: Install Pulumi CLI
      if: inputs.tools == 'all' || contains(inputs.tools, 'pulumicli')
      uses: pulumi/actions@13b8b7177d6fb736766875dac9b78aab07bd785f # v6
      with:
        pulumi-version: "dev"

    - name: Install Schema Tools
      if: inputs.tools == 'all' || contains(inputs.tools, 'schema-tools')
      uses: jaxxstorm/action-install-gh-release@cd6b2b78ad38bdd294341cda064ec0692b06215b # v1.14.0
      with:
        repo: pulumi/schema-tools

    - name: Setup Node
      if: inputs.tools == 'all' || contains(inputs.tools, 'nodejs')
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        node-version: 20.x
        registry-url: https://registry.npmjs.org

    - name: Setup DotNet
      if: inputs.tools == 'all' || contains(inputs.tools, 'dotnet')
      uses: actions/setup-dotnet@87b7050bc53ea08284295505d98d2aa94301e852 # v4.2.0
      with:
        dotnet-version: 6.0.x

    - name: Setup Python
      if: inputs.tools == 'all' || contains(inputs.tools, 'python')
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: 3.11.8

    - name: Setup Java
      if: inputs.tools == 'all' || contains(inputs.tools, 'java')
      uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
      with:
        cache: gradle
        distribution: temurin
        java-version: 11

    - name: Setup Gradle
      if: inputs.tools == 'all' || contains(inputs.tools, 'java')
      uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3
      with:
        gradle-version: 7.6
