// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aws.s3.outputs;

import com.pulumi.aws.s3.outputs.BucketMetadataConfigurationMetadataConfigurationJournalTableConfigurationEncryptionConfiguration;
import com.pulumi.aws.s3.outputs.BucketMetadataConfigurationMetadataConfigurationJournalTableConfigurationRecordExpiration;
import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class BucketMetadataConfigurationMetadataConfigurationJournalTableConfiguration {
    private @Nullable BucketMetadataConfigurationMetadataConfigurationJournalTableConfigurationEncryptionConfiguration encryptionConfiguration;
    private @Nullable BucketMetadataConfigurationMetadataConfigurationJournalTableConfigurationRecordExpiration recordExpiration;
    private @Nullable String tableArn;
    private @Nullable String tableName;

    private BucketMetadataConfigurationMetadataConfigurationJournalTableConfiguration() {}
    public Optional<BucketMetadataConfigurationMetadataConfigurationJournalTableConfigurationEncryptionConfiguration> encryptionConfiguration() {
        return Optional.ofNullable(this.encryptionConfiguration);
    }
    public Optional<BucketMetadataConfigurationMetadataConfigurationJournalTableConfigurationRecordExpiration> recordExpiration() {
        return Optional.ofNullable(this.recordExpiration);
    }
    public Optional<String> tableArn() {
        return Optional.ofNullable(this.tableArn);
    }
    public Optional<String> tableName() {
        return Optional.ofNullable(this.tableName);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(BucketMetadataConfigurationMetadataConfigurationJournalTableConfiguration defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable BucketMetadataConfigurationMetadataConfigurationJournalTableConfigurationEncryptionConfiguration encryptionConfiguration;
        private @Nullable BucketMetadataConfigurationMetadataConfigurationJournalTableConfigurationRecordExpiration recordExpiration;
        private @Nullable String tableArn;
        private @Nullable String tableName;
        public Builder() {}
        public Builder(BucketMetadataConfigurationMetadataConfigurationJournalTableConfiguration defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.encryptionConfiguration = defaults.encryptionConfiguration;
    	      this.recordExpiration = defaults.recordExpiration;
    	      this.tableArn = defaults.tableArn;
    	      this.tableName = defaults.tableName;
        }

        @CustomType.Setter
        public Builder encryptionConfiguration(@Nullable BucketMetadataConfigurationMetadataConfigurationJournalTableConfigurationEncryptionConfiguration encryptionConfiguration) {

            this.encryptionConfiguration = encryptionConfiguration;
            return this;
        }
        @CustomType.Setter
        public Builder recordExpiration(@Nullable BucketMetadataConfigurationMetadataConfigurationJournalTableConfigurationRecordExpiration recordExpiration) {

            this.recordExpiration = recordExpiration;
            return this;
        }
        @CustomType.Setter
        public Builder tableArn(@Nullable String tableArn) {

            this.tableArn = tableArn;
            return this;
        }
        @CustomType.Setter
        public Builder tableName(@Nullable String tableName) {

            this.tableName = tableName;
            return this;
        }
        public BucketMetadataConfigurationMetadataConfigurationJournalTableConfiguration build() {
            final var _resultValue = new BucketMetadataConfigurationMetadataConfigurationJournalTableConfiguration();
            _resultValue.encryptionConfiguration = encryptionConfiguration;
            _resultValue.recordExpiration = recordExpiration;
            _resultValue.tableArn = tableArn;
            _resultValue.tableName = tableName;
            return _resultValue;
        }
    }
}
