// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.PolicyPacks.Aws.CloudWatch
{
    [PolicyResourceType("aws:cloudwatch/eventApiDestination:EventApiDestination")]
    public sealed class EventApiDestination : global::Pulumi.PolicyResourceOutput
    {
        /// <summary>
        /// The Amazon Resource Name (ARN) of the event API Destination.
        /// </summary>
        [PolicyResourceProperty("arn", "_mUnknown_Arn")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private string? _mValue_Arn;
        private bool _mUnknown_Arn;
        public string? Arn
        {
            get
            {
                if (!_mUnknown_Arn) return _mValue_Arn;
                throw new UndeferrableValueException("Value 'EventApiDestination.Arn' is not present");
            }
        }

        /// <summary>
        /// ARN of the EventBridge Connection to use for the API Destination.
        /// </summary>
        [PolicyResourceProperty("connectionArn", "_mUnknown_ConnectionArn")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private string? _mValue_ConnectionArn;
        private bool _mUnknown_ConnectionArn;
        public string? ConnectionArn
        {
            get
            {
                if (!_mUnknown_ConnectionArn) return _mValue_ConnectionArn;
                throw new UndeferrableValueException("Value 'EventApiDestination.ConnectionArn' is not present");
            }
        }

        /// <summary>
        /// The description of the new API Destination. Maximum of 512 characters.
        /// </summary>
        [PolicyResourceProperty("description", "_mUnknown_Description")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private string? _mValue_Description;
        private bool _mUnknown_Description;
        public string? Description
        {
            get
            {
                if (!_mUnknown_Description) return _mValue_Description;
                throw new UndeferrableValueException("Value 'EventApiDestination.Description' is not present");
            }
        }

        /// <summary>
        /// Select the HTTP method used for the invocation endpoint, such as GET, POST, PUT, etc.
        /// </summary>
        [PolicyResourceProperty("httpMethod", "_mUnknown_HttpMethod")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private string? _mValue_HttpMethod;
        private bool _mUnknown_HttpMethod;
        public string? HttpMethod
        {
            get
            {
                if (!_mUnknown_HttpMethod) return _mValue_HttpMethod;
                throw new UndeferrableValueException("Value 'EventApiDestination.HttpMethod' is not present");
            }
        }

        /// <summary>
        /// URL endpoint to invoke as a target. This could be a valid endpoint generated by a partner service. You can include "*" as path parameters wildcards to be set from the Target HttpParameters.
        /// </summary>
        [PolicyResourceProperty("invocationEndpoint", "_mUnknown_InvocationEndpoint")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private string? _mValue_InvocationEndpoint;
        private bool _mUnknown_InvocationEndpoint;
        public string? InvocationEndpoint
        {
            get
            {
                if (!_mUnknown_InvocationEndpoint) return _mValue_InvocationEndpoint;
                throw new UndeferrableValueException("Value 'EventApiDestination.InvocationEndpoint' is not present");
            }
        }

        /// <summary>
        /// Enter the maximum number of invocations per second to allow for this destination. Enter a value greater than 0 (default 300).
        /// </summary>
        [PolicyResourceProperty("invocationRateLimitPerSecond", "_mUnknown_InvocationRateLimitPerSecond")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private int? _mValue_InvocationRateLimitPerSecond;
        private bool _mUnknown_InvocationRateLimitPerSecond;
        public int? InvocationRateLimitPerSecond
        {
            get
            {
                if (!_mUnknown_InvocationRateLimitPerSecond) return _mValue_InvocationRateLimitPerSecond;
                throw new UndeferrableValueException("Value 'EventApiDestination.InvocationRateLimitPerSecond' is not present");
            }
        }

        /// <summary>
        /// The name of the new API Destination. The name must be unique for your account. Maximum of 64 characters consisting of numbers, lower/upper case letters, .,-,_.
        /// </summary>
        [PolicyResourceProperty("name", "_mUnknown_Name")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private string? _mValue_Name;
        private bool _mUnknown_Name;
        public string? Name
        {
            get
            {
                if (!_mUnknown_Name) return _mValue_Name;
                throw new UndeferrableValueException("Value 'EventApiDestination.Name' is not present");
            }
        }
    }

    [PolicyResourceType("aws:cloudwatch/eventApiDestination:EventApiDestination")]
    public sealed class EventApiDestinationArgs : global::Pulumi.PolicyResourceInput
    {
        /// <summary>
        /// ARN of the EventBridge Connection to use for the API Destination.
        /// </summary>
        [PolicyResourceProperty("connectionArn", "_mUnknown_ConnectionArn")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private string? _mValue_ConnectionArn;
        private bool _mUnknown_ConnectionArn;
        public string? ConnectionArn
        {
            get
            {
                if (!_mUnknown_ConnectionArn) return _mValue_ConnectionArn;
                throw new UndeferrableValueException("Value 'EventApiDestinationArgs.ConnectionArn' is not present");
            }
        }

        /// <summary>
        /// The description of the new API Destination. Maximum of 512 characters.
        /// </summary>
        [PolicyResourceProperty("description", "_mUnknown_Description")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private string? _mValue_Description;
        private bool _mUnknown_Description;
        public string? Description
        {
            get
            {
                if (!_mUnknown_Description) return _mValue_Description;
                throw new UndeferrableValueException("Value 'EventApiDestinationArgs.Description' is not present");
            }
        }

        /// <summary>
        /// Select the HTTP method used for the invocation endpoint, such as GET, POST, PUT, etc.
        /// </summary>
        [PolicyResourceProperty("httpMethod", "_mUnknown_HttpMethod")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private string? _mValue_HttpMethod;
        private bool _mUnknown_HttpMethod;
        public string? HttpMethod
        {
            get
            {
                if (!_mUnknown_HttpMethod) return _mValue_HttpMethod;
                throw new UndeferrableValueException("Value 'EventApiDestinationArgs.HttpMethod' is not present");
            }
        }

        /// <summary>
        /// URL endpoint to invoke as a target. This could be a valid endpoint generated by a partner service. You can include "*" as path parameters wildcards to be set from the Target HttpParameters.
        /// </summary>
        [PolicyResourceProperty("invocationEndpoint", "_mUnknown_InvocationEndpoint")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private string? _mValue_InvocationEndpoint;
        private bool _mUnknown_InvocationEndpoint;
        public string? InvocationEndpoint
        {
            get
            {
                if (!_mUnknown_InvocationEndpoint) return _mValue_InvocationEndpoint;
                throw new UndeferrableValueException("Value 'EventApiDestinationArgs.InvocationEndpoint' is not present");
            }
        }

        /// <summary>
        /// Enter the maximum number of invocations per second to allow for this destination. Enter a value greater than 0 (default 300).
        /// </summary>
        [PolicyResourceProperty("invocationRateLimitPerSecond", "_mUnknown_InvocationRateLimitPerSecond")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private int? _mValue_InvocationRateLimitPerSecond;
        private bool _mUnknown_InvocationRateLimitPerSecond;
        public int? InvocationRateLimitPerSecond
        {
            get
            {
                if (!_mUnknown_InvocationRateLimitPerSecond) return _mValue_InvocationRateLimitPerSecond;
                throw new UndeferrableValueException("Value 'EventApiDestinationArgs.InvocationRateLimitPerSecond' is not present");
            }
        }

        /// <summary>
        /// The name of the new API Destination. The name must be unique for your account. Maximum of 64 characters consisting of numbers, lower/upper case letters, .,-,_.
        /// </summary>
        [PolicyResourceProperty("name", "_mUnknown_Name")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private string? _mValue_Name;
        private bool _mUnknown_Name;
        public string? Name
        {
            get
            {
                if (!_mUnknown_Name) return _mValue_Name;
                throw new UndeferrableValueException("Value 'EventApiDestinationArgs.Name' is not present");
            }
        }
    }
}
