// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aws.iot;

import com.pulumi.aws.Utilities;
import com.pulumi.aws.iot.CertificateArgs;
import com.pulumi.aws.iot.inputs.CertificateState;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="aws:iot/certificate:Certificate")
public class Certificate extends com.pulumi.resources.CustomResource {
    @Export(name="active", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> active;

    public Output<Boolean> active() {
        return this.active;
    }
    @Export(name="arn", refs={String.class}, tree="[0]")
    private Output<String> arn;

    public Output<String> arn() {
        return this.arn;
    }
    @Export(name="caCertificateId", refs={String.class}, tree="[0]")
    private Output<String> caCertificateId;

    public Output<String> caCertificateId() {
        return this.caCertificateId;
    }
    @Export(name="caPem", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> caPem;

    public Output<Optional<String>> caPem() {
        return Codegen.optional(this.caPem);
    }
    @Export(name="certificatePem", refs={String.class}, tree="[0]")
    private Output<String> certificatePem;

    public Output<String> certificatePem() {
        return this.certificatePem;
    }
    @Export(name="csr", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> csr;

    public Output<Optional<String>> csr() {
        return Codegen.optional(this.csr);
    }
    @Export(name="privateKey", refs={String.class}, tree="[0]")
    private Output<String> privateKey;

    public Output<String> privateKey() {
        return this.privateKey;
    }
    @Export(name="publicKey", refs={String.class}, tree="[0]")
    private Output<String> publicKey;

    public Output<String> publicKey() {
        return this.publicKey;
    }
    @Export(name="region", refs={String.class}, tree="[0]")
    private Output<String> region;

    public Output<String> region() {
        return this.region;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Certificate(java.lang.String name) {
        this(name, CertificateArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Certificate(java.lang.String name, CertificateArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Certificate(java.lang.String name, CertificateArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("aws:iot/certificate:Certificate", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Certificate(java.lang.String name, Output<java.lang.String> id, @Nullable CertificateState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("aws:iot/certificate:Certificate", name, state, makeResourceOptions(options, id), false);
    }

    private static CertificateArgs makeArgs(CertificateArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? CertificateArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "caPem",
                "certificatePem",
                "privateKey",
                "publicKey"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Certificate get(java.lang.String name, Output<java.lang.String> id, @Nullable CertificateState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Certificate(name, id, state, options);
    }
}
