// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.policypacks.aws.cloudwatch;

import java.lang.String;


public final class EventTargetSqsTarget {

    /**
     * The FIFO message group ID to use as the target.
     * 
     */
    public String messageGroupId;



}
