// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aws.OpenSearch.Inputs
{

    public sealed class DomainAimlOptionsS3VectorsEngineGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enables S3 vectors engine features.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        public DomainAimlOptionsS3VectorsEngineGetArgs()
        {
        }
        public static new DomainAimlOptionsS3VectorsEngineGetArgs Empty => new DomainAimlOptionsS3VectorsEngineGetArgs();
    }
}
