// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.policypacks.aws.directoryservice;

import com.pulumi.core.UndeferrableValue;
import com.pulumi.core.annotations.PolicyResourceType;
import com.pulumi.policypacks.aws.directoryservice.outputs.ServiceRegionVpcSettings;
import java.lang.Integer;
import java.lang.String;
import java.util.Map;
import javax.annotation.Nullable;


@PolicyResourceType(type="aws:directoryservice/serviceRegion:ServiceRegion")
public final class ServiceRegion extends com.pulumi.resources.PolicyResourceOutput {

    /**
     * The number of domain controllers desired in the replicated directory. Minimum value of `2`.
     * 
     */
    private UndeferrableValue<Integer> desiredNumberOfDomainControllers;

    public Integer desiredNumberOfDomainControllers() {
        if (desiredNumberOfDomainControllers == null) return null;
        return desiredNumberOfDomainControllers.getValue("ServiceRegion.desiredNumberOfDomainControllers");
    }

    /**
     * The identifier of the directory to which you want to add Region replication.
     * 
     */
    private UndeferrableValue<String> directoryId;

    public String directoryId() {
        if (directoryId == null) return null;
        return directoryId.getValue("ServiceRegion.directoryId");
    }

    /**
     * The name of the Region where you want to add domain controllers for replication.
     * 
     */
    private UndeferrableValue<String> regionName;

    public String regionName() {
        if (regionName == null) return null;
        return regionName.getValue("ServiceRegion.regionName");
    }

    /**
     * Map of tags to assign to this resource. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
     * 
     */
    private @Nullable UndeferrableValue<Map<String,String>> tags;

    public @Nullable Map<String,String> tags() {
        if (tags == null) return null;
        return tags.getValue("ServiceRegion.tags");
    }

    /**
     * A map of tags assigned to the resource, including those inherited from the provider `default_tags` configuration block.
     * 
     * @deprecated
     * Please use `tags` instead.
     * 
     */
    @Deprecated /* Please use `tags` instead. */
    private UndeferrableValue<Map<String,String>> tagsAll;

    public Map<String,String> tagsAll() {
        if (tagsAll == null) return null;
        return tagsAll.getValue("ServiceRegion.tagsAll");
    }

    /**
     * VPC information in the replicated Region. Detailed below.
     * 
     */
    private UndeferrableValue<ServiceRegionVpcSettings> vpcSettings;

    public ServiceRegionVpcSettings vpcSettings() {
        if (vpcSettings == null) return null;
        return vpcSettings.getValue("ServiceRegion.vpcSettings");
    }

}
