name: Upload SDK asset
description: Upload the SDK for a specific language as an asset for the workflow.

runs:
  using: "composite"
  steps:
    - name: Capture executable permissions
      shell: bash
      run: find bin -type f -executable > bin/executables.txt

    - name: Upload prerequisites bin
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: prerequisites-bin
        path: bin/*
        retention-days: 30

    - name: Upload schema-embed.json
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: schema-embed.json
        path: provider/cmd/pulumi-resource-aws/schema-embed.json
        retention-days: 30
