name: Upload SDK asset
description: Upload the SDK for a specific language as an asset for the workflow.

runs:
  using: "composite"
  steps:
    - name: Capture executable permissions
      shell: bash
      run: find bin -type f -executable > bin/executables.txt

    - name: Upload prerequisites bin
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: prerequisites-bin
        path: bin/*
        retention-days: 30

    - name: Upload schema-embed.json
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: schema-embed.json
        path: provider/cmd/pulumi-resource-aws/schema-embed.json
        retention-days: 30
