// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package iot

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-aws/sdk/v7/go/aws/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type TopicRule struct {
	pulumi.CustomResourceState

	Arn               pulumi.StringOutput                  `pulumi:"arn"`
	CloudwatchAlarms  TopicRuleCloudwatchAlarmArrayOutput  `pulumi:"cloudwatchAlarms"`
	CloudwatchLogs    TopicRuleCloudwatchLogArrayOutput    `pulumi:"cloudwatchLogs"`
	CloudwatchMetrics TopicRuleCloudwatchMetricArrayOutput `pulumi:"cloudwatchMetrics"`
	Description       pulumi.StringPtrOutput               `pulumi:"description"`
	Dynamodbs         TopicRuleDynamodbArrayOutput         `pulumi:"dynamodbs"`
	Dynamodbv2s       TopicRuleDynamodbv2ArrayOutput       `pulumi:"dynamodbv2s"`
	Elasticsearch     TopicRuleElasticsearchArrayOutput    `pulumi:"elasticsearch"`
	Enabled           pulumi.BoolOutput                    `pulumi:"enabled"`
	ErrorAction       TopicRuleErrorActionPtrOutput        `pulumi:"errorAction"`
	Firehoses         TopicRuleFirehoseArrayOutput         `pulumi:"firehoses"`
	Https             TopicRuleHttpArrayOutput             `pulumi:"https"`
	IotAnalytics      TopicRuleIotAnalyticArrayOutput      `pulumi:"iotAnalytics"`
	IotEvents         TopicRuleIotEventArrayOutput         `pulumi:"iotEvents"`
	Kafkas            TopicRuleKafkaArrayOutput            `pulumi:"kafkas"`
	Kineses           TopicRuleKinesisArrayOutput          `pulumi:"kineses"`
	Lambdas           TopicRuleLambdaArrayOutput           `pulumi:"lambdas"`
	Name              pulumi.StringOutput                  `pulumi:"name"`
	Region            pulumi.StringOutput                  `pulumi:"region"`
	Republishes       TopicRuleRepublishArrayOutput        `pulumi:"republishes"`
	S3                TopicRuleS3ArrayOutput               `pulumi:"s3"`
	Sns               TopicRuleSnsArrayOutput              `pulumi:"sns"`
	Sql               pulumi.StringOutput                  `pulumi:"sql"`
	SqlVersion        pulumi.StringOutput                  `pulumi:"sqlVersion"`
	Sqs               TopicRuleSqsArrayOutput              `pulumi:"sqs"`
	StepFunctions     TopicRuleStepFunctionArrayOutput     `pulumi:"stepFunctions"`
	Tags              pulumi.StringMapOutput               `pulumi:"tags"`
	TagsAll           pulumi.StringMapOutput               `pulumi:"tagsAll"`
	Timestreams       TopicRuleTimestreamArrayOutput       `pulumi:"timestreams"`
}

// NewTopicRule registers a new resource with the given unique name, arguments, and options.
func NewTopicRule(ctx *pulumi.Context,
	name string, args *TopicRuleArgs, opts ...pulumi.ResourceOption) (*TopicRule, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Enabled == nil {
		return nil, errors.New("invalid value for required argument 'Enabled'")
	}
	if args.Sql == nil {
		return nil, errors.New("invalid value for required argument 'Sql'")
	}
	if args.SqlVersion == nil {
		return nil, errors.New("invalid value for required argument 'SqlVersion'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource TopicRule
	err := ctx.RegisterResource("aws:iot/topicRule:TopicRule", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTopicRule gets an existing TopicRule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTopicRule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TopicRuleState, opts ...pulumi.ResourceOption) (*TopicRule, error) {
	var resource TopicRule
	err := ctx.ReadResource("aws:iot/topicRule:TopicRule", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering TopicRule resources.
type topicRuleState struct {
	Arn               *string                     `pulumi:"arn"`
	CloudwatchAlarms  []TopicRuleCloudwatchAlarm  `pulumi:"cloudwatchAlarms"`
	CloudwatchLogs    []TopicRuleCloudwatchLog    `pulumi:"cloudwatchLogs"`
	CloudwatchMetrics []TopicRuleCloudwatchMetric `pulumi:"cloudwatchMetrics"`
	Description       *string                     `pulumi:"description"`
	Dynamodbs         []TopicRuleDynamodb         `pulumi:"dynamodbs"`
	Dynamodbv2s       []TopicRuleDynamodbv2       `pulumi:"dynamodbv2s"`
	Elasticsearch     []TopicRuleElasticsearch    `pulumi:"elasticsearch"`
	Enabled           *bool                       `pulumi:"enabled"`
	ErrorAction       *TopicRuleErrorAction       `pulumi:"errorAction"`
	Firehoses         []TopicRuleFirehose         `pulumi:"firehoses"`
	Https             []TopicRuleHttp             `pulumi:"https"`
	IotAnalytics      []TopicRuleIotAnalytic      `pulumi:"iotAnalytics"`
	IotEvents         []TopicRuleIotEvent         `pulumi:"iotEvents"`
	Kafkas            []TopicRuleKafka            `pulumi:"kafkas"`
	Kineses           []TopicRuleKinesis          `pulumi:"kineses"`
	Lambdas           []TopicRuleLambda           `pulumi:"lambdas"`
	Name              *string                     `pulumi:"name"`
	Region            *string                     `pulumi:"region"`
	Republishes       []TopicRuleRepublish        `pulumi:"republishes"`
	S3                []TopicRuleS3               `pulumi:"s3"`
	Sns               []TopicRuleSns              `pulumi:"sns"`
	Sql               *string                     `pulumi:"sql"`
	SqlVersion        *string                     `pulumi:"sqlVersion"`
	Sqs               []TopicRuleSqs              `pulumi:"sqs"`
	StepFunctions     []TopicRuleStepFunction     `pulumi:"stepFunctions"`
	Tags              map[string]string           `pulumi:"tags"`
	TagsAll           map[string]string           `pulumi:"tagsAll"`
	Timestreams       []TopicRuleTimestream       `pulumi:"timestreams"`
}

type TopicRuleState struct {
	Arn               pulumi.StringPtrInput
	CloudwatchAlarms  TopicRuleCloudwatchAlarmArrayInput
	CloudwatchLogs    TopicRuleCloudwatchLogArrayInput
	CloudwatchMetrics TopicRuleCloudwatchMetricArrayInput
	Description       pulumi.StringPtrInput
	Dynamodbs         TopicRuleDynamodbArrayInput
	Dynamodbv2s       TopicRuleDynamodbv2ArrayInput
	Elasticsearch     TopicRuleElasticsearchArrayInput
	Enabled           pulumi.BoolPtrInput
	ErrorAction       TopicRuleErrorActionPtrInput
	Firehoses         TopicRuleFirehoseArrayInput
	Https             TopicRuleHttpArrayInput
	IotAnalytics      TopicRuleIotAnalyticArrayInput
	IotEvents         TopicRuleIotEventArrayInput
	Kafkas            TopicRuleKafkaArrayInput
	Kineses           TopicRuleKinesisArrayInput
	Lambdas           TopicRuleLambdaArrayInput
	Name              pulumi.StringPtrInput
	Region            pulumi.StringPtrInput
	Republishes       TopicRuleRepublishArrayInput
	S3                TopicRuleS3ArrayInput
	Sns               TopicRuleSnsArrayInput
	Sql               pulumi.StringPtrInput
	SqlVersion        pulumi.StringPtrInput
	Sqs               TopicRuleSqsArrayInput
	StepFunctions     TopicRuleStepFunctionArrayInput
	Tags              pulumi.StringMapInput
	TagsAll           pulumi.StringMapInput
	Timestreams       TopicRuleTimestreamArrayInput
}

func (TopicRuleState) ElementType() reflect.Type {
	return reflect.TypeOf((*topicRuleState)(nil)).Elem()
}

type topicRuleArgs struct {
	CloudwatchAlarms  []TopicRuleCloudwatchAlarm  `pulumi:"cloudwatchAlarms"`
	CloudwatchLogs    []TopicRuleCloudwatchLog    `pulumi:"cloudwatchLogs"`
	CloudwatchMetrics []TopicRuleCloudwatchMetric `pulumi:"cloudwatchMetrics"`
	Description       *string                     `pulumi:"description"`
	Dynamodbs         []TopicRuleDynamodb         `pulumi:"dynamodbs"`
	Dynamodbv2s       []TopicRuleDynamodbv2       `pulumi:"dynamodbv2s"`
	Elasticsearch     []TopicRuleElasticsearch    `pulumi:"elasticsearch"`
	Enabled           bool                        `pulumi:"enabled"`
	ErrorAction       *TopicRuleErrorAction       `pulumi:"errorAction"`
	Firehoses         []TopicRuleFirehose         `pulumi:"firehoses"`
	Https             []TopicRuleHttp             `pulumi:"https"`
	IotAnalytics      []TopicRuleIotAnalytic      `pulumi:"iotAnalytics"`
	IotEvents         []TopicRuleIotEvent         `pulumi:"iotEvents"`
	Kafkas            []TopicRuleKafka            `pulumi:"kafkas"`
	Kineses           []TopicRuleKinesis          `pulumi:"kineses"`
	Lambdas           []TopicRuleLambda           `pulumi:"lambdas"`
	Name              *string                     `pulumi:"name"`
	Region            *string                     `pulumi:"region"`
	Republishes       []TopicRuleRepublish        `pulumi:"republishes"`
	S3                []TopicRuleS3               `pulumi:"s3"`
	Sns               []TopicRuleSns              `pulumi:"sns"`
	Sql               string                      `pulumi:"sql"`
	SqlVersion        string                      `pulumi:"sqlVersion"`
	Sqs               []TopicRuleSqs              `pulumi:"sqs"`
	StepFunctions     []TopicRuleStepFunction     `pulumi:"stepFunctions"`
	Tags              map[string]string           `pulumi:"tags"`
	Timestreams       []TopicRuleTimestream       `pulumi:"timestreams"`
}

// The set of arguments for constructing a TopicRule resource.
type TopicRuleArgs struct {
	CloudwatchAlarms  TopicRuleCloudwatchAlarmArrayInput
	CloudwatchLogs    TopicRuleCloudwatchLogArrayInput
	CloudwatchMetrics TopicRuleCloudwatchMetricArrayInput
	Description       pulumi.StringPtrInput
	Dynamodbs         TopicRuleDynamodbArrayInput
	Dynamodbv2s       TopicRuleDynamodbv2ArrayInput
	Elasticsearch     TopicRuleElasticsearchArrayInput
	Enabled           pulumi.BoolInput
	ErrorAction       TopicRuleErrorActionPtrInput
	Firehoses         TopicRuleFirehoseArrayInput
	Https             TopicRuleHttpArrayInput
	IotAnalytics      TopicRuleIotAnalyticArrayInput
	IotEvents         TopicRuleIotEventArrayInput
	Kafkas            TopicRuleKafkaArrayInput
	Kineses           TopicRuleKinesisArrayInput
	Lambdas           TopicRuleLambdaArrayInput
	Name              pulumi.StringPtrInput
	Region            pulumi.StringPtrInput
	Republishes       TopicRuleRepublishArrayInput
	S3                TopicRuleS3ArrayInput
	Sns               TopicRuleSnsArrayInput
	Sql               pulumi.StringInput
	SqlVersion        pulumi.StringInput
	Sqs               TopicRuleSqsArrayInput
	StepFunctions     TopicRuleStepFunctionArrayInput
	Tags              pulumi.StringMapInput
	Timestreams       TopicRuleTimestreamArrayInput
}

func (TopicRuleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*topicRuleArgs)(nil)).Elem()
}

type TopicRuleInput interface {
	pulumi.Input

	ToTopicRuleOutput() TopicRuleOutput
	ToTopicRuleOutputWithContext(ctx context.Context) TopicRuleOutput
}

func (*TopicRule) ElementType() reflect.Type {
	return reflect.TypeOf((**TopicRule)(nil)).Elem()
}

func (i *TopicRule) ToTopicRuleOutput() TopicRuleOutput {
	return i.ToTopicRuleOutputWithContext(context.Background())
}

func (i *TopicRule) ToTopicRuleOutputWithContext(ctx context.Context) TopicRuleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TopicRuleOutput)
}

// TopicRuleArrayInput is an input type that accepts TopicRuleArray and TopicRuleArrayOutput values.
// You can construct a concrete instance of `TopicRuleArrayInput` via:
//
//	TopicRuleArray{ TopicRuleArgs{...} }
type TopicRuleArrayInput interface {
	pulumi.Input

	ToTopicRuleArrayOutput() TopicRuleArrayOutput
	ToTopicRuleArrayOutputWithContext(context.Context) TopicRuleArrayOutput
}

type TopicRuleArray []TopicRuleInput

func (TopicRuleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*TopicRule)(nil)).Elem()
}

func (i TopicRuleArray) ToTopicRuleArrayOutput() TopicRuleArrayOutput {
	return i.ToTopicRuleArrayOutputWithContext(context.Background())
}

func (i TopicRuleArray) ToTopicRuleArrayOutputWithContext(ctx context.Context) TopicRuleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TopicRuleArrayOutput)
}

// TopicRuleMapInput is an input type that accepts TopicRuleMap and TopicRuleMapOutput values.
// You can construct a concrete instance of `TopicRuleMapInput` via:
//
//	TopicRuleMap{ "key": TopicRuleArgs{...} }
type TopicRuleMapInput interface {
	pulumi.Input

	ToTopicRuleMapOutput() TopicRuleMapOutput
	ToTopicRuleMapOutputWithContext(context.Context) TopicRuleMapOutput
}

type TopicRuleMap map[string]TopicRuleInput

func (TopicRuleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*TopicRule)(nil)).Elem()
}

func (i TopicRuleMap) ToTopicRuleMapOutput() TopicRuleMapOutput {
	return i.ToTopicRuleMapOutputWithContext(context.Background())
}

func (i TopicRuleMap) ToTopicRuleMapOutputWithContext(ctx context.Context) TopicRuleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TopicRuleMapOutput)
}

type TopicRuleOutput struct{ *pulumi.OutputState }

func (TopicRuleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TopicRule)(nil)).Elem()
}

func (o TopicRuleOutput) ToTopicRuleOutput() TopicRuleOutput {
	return o
}

func (o TopicRuleOutput) ToTopicRuleOutputWithContext(ctx context.Context) TopicRuleOutput {
	return o
}

func (o TopicRuleOutput) Arn() pulumi.StringOutput {
	return o.ApplyT(func(v *TopicRule) pulumi.StringOutput { return v.Arn }).(pulumi.StringOutput)
}

func (o TopicRuleOutput) CloudwatchAlarms() TopicRuleCloudwatchAlarmArrayOutput {
	return o.ApplyT(func(v *TopicRule) TopicRuleCloudwatchAlarmArrayOutput { return v.CloudwatchAlarms }).(TopicRuleCloudwatchAlarmArrayOutput)
}

func (o TopicRuleOutput) CloudwatchLogs() TopicRuleCloudwatchLogArrayOutput {
	return o.ApplyT(func(v *TopicRule) TopicRuleCloudwatchLogArrayOutput { return v.CloudwatchLogs }).(TopicRuleCloudwatchLogArrayOutput)
}

func (o TopicRuleOutput) CloudwatchMetrics() TopicRuleCloudwatchMetricArrayOutput {
	return o.ApplyT(func(v *TopicRule) TopicRuleCloudwatchMetricArrayOutput { return v.CloudwatchMetrics }).(TopicRuleCloudwatchMetricArrayOutput)
}

func (o TopicRuleOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TopicRule) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

func (o TopicRuleOutput) Dynamodbs() TopicRuleDynamodbArrayOutput {
	return o.ApplyT(func(v *TopicRule) TopicRuleDynamodbArrayOutput { return v.Dynamodbs }).(TopicRuleDynamodbArrayOutput)
}

func (o TopicRuleOutput) Dynamodbv2s() TopicRuleDynamodbv2ArrayOutput {
	return o.ApplyT(func(v *TopicRule) TopicRuleDynamodbv2ArrayOutput { return v.Dynamodbv2s }).(TopicRuleDynamodbv2ArrayOutput)
}

func (o TopicRuleOutput) Elasticsearch() TopicRuleElasticsearchArrayOutput {
	return o.ApplyT(func(v *TopicRule) TopicRuleElasticsearchArrayOutput { return v.Elasticsearch }).(TopicRuleElasticsearchArrayOutput)
}

func (o TopicRuleOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *TopicRule) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

func (o TopicRuleOutput) ErrorAction() TopicRuleErrorActionPtrOutput {
	return o.ApplyT(func(v *TopicRule) TopicRuleErrorActionPtrOutput { return v.ErrorAction }).(TopicRuleErrorActionPtrOutput)
}

func (o TopicRuleOutput) Firehoses() TopicRuleFirehoseArrayOutput {
	return o.ApplyT(func(v *TopicRule) TopicRuleFirehoseArrayOutput { return v.Firehoses }).(TopicRuleFirehoseArrayOutput)
}

func (o TopicRuleOutput) Https() TopicRuleHttpArrayOutput {
	return o.ApplyT(func(v *TopicRule) TopicRuleHttpArrayOutput { return v.Https }).(TopicRuleHttpArrayOutput)
}

func (o TopicRuleOutput) IotAnalytics() TopicRuleIotAnalyticArrayOutput {
	return o.ApplyT(func(v *TopicRule) TopicRuleIotAnalyticArrayOutput { return v.IotAnalytics }).(TopicRuleIotAnalyticArrayOutput)
}

func (o TopicRuleOutput) IotEvents() TopicRuleIotEventArrayOutput {
	return o.ApplyT(func(v *TopicRule) TopicRuleIotEventArrayOutput { return v.IotEvents }).(TopicRuleIotEventArrayOutput)
}

func (o TopicRuleOutput) Kafkas() TopicRuleKafkaArrayOutput {
	return o.ApplyT(func(v *TopicRule) TopicRuleKafkaArrayOutput { return v.Kafkas }).(TopicRuleKafkaArrayOutput)
}

func (o TopicRuleOutput) Kineses() TopicRuleKinesisArrayOutput {
	return o.ApplyT(func(v *TopicRule) TopicRuleKinesisArrayOutput { return v.Kineses }).(TopicRuleKinesisArrayOutput)
}

func (o TopicRuleOutput) Lambdas() TopicRuleLambdaArrayOutput {
	return o.ApplyT(func(v *TopicRule) TopicRuleLambdaArrayOutput { return v.Lambdas }).(TopicRuleLambdaArrayOutput)
}

func (o TopicRuleOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *TopicRule) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o TopicRuleOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *TopicRule) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

func (o TopicRuleOutput) Republishes() TopicRuleRepublishArrayOutput {
	return o.ApplyT(func(v *TopicRule) TopicRuleRepublishArrayOutput { return v.Republishes }).(TopicRuleRepublishArrayOutput)
}

func (o TopicRuleOutput) S3() TopicRuleS3ArrayOutput {
	return o.ApplyT(func(v *TopicRule) TopicRuleS3ArrayOutput { return v.S3 }).(TopicRuleS3ArrayOutput)
}

func (o TopicRuleOutput) Sns() TopicRuleSnsArrayOutput {
	return o.ApplyT(func(v *TopicRule) TopicRuleSnsArrayOutput { return v.Sns }).(TopicRuleSnsArrayOutput)
}

func (o TopicRuleOutput) Sql() pulumi.StringOutput {
	return o.ApplyT(func(v *TopicRule) pulumi.StringOutput { return v.Sql }).(pulumi.StringOutput)
}

func (o TopicRuleOutput) SqlVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *TopicRule) pulumi.StringOutput { return v.SqlVersion }).(pulumi.StringOutput)
}

func (o TopicRuleOutput) Sqs() TopicRuleSqsArrayOutput {
	return o.ApplyT(func(v *TopicRule) TopicRuleSqsArrayOutput { return v.Sqs }).(TopicRuleSqsArrayOutput)
}

func (o TopicRuleOutput) StepFunctions() TopicRuleStepFunctionArrayOutput {
	return o.ApplyT(func(v *TopicRule) TopicRuleStepFunctionArrayOutput { return v.StepFunctions }).(TopicRuleStepFunctionArrayOutput)
}

func (o TopicRuleOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v *TopicRule) pulumi.StringMapOutput { return v.Tags }).(pulumi.StringMapOutput)
}

func (o TopicRuleOutput) TagsAll() pulumi.StringMapOutput {
	return o.ApplyT(func(v *TopicRule) pulumi.StringMapOutput { return v.TagsAll }).(pulumi.StringMapOutput)
}

func (o TopicRuleOutput) Timestreams() TopicRuleTimestreamArrayOutput {
	return o.ApplyT(func(v *TopicRule) TopicRuleTimestreamArrayOutput { return v.Timestreams }).(TopicRuleTimestreamArrayOutput)
}

type TopicRuleArrayOutput struct{ *pulumi.OutputState }

func (TopicRuleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*TopicRule)(nil)).Elem()
}

func (o TopicRuleArrayOutput) ToTopicRuleArrayOutput() TopicRuleArrayOutput {
	return o
}

func (o TopicRuleArrayOutput) ToTopicRuleArrayOutputWithContext(ctx context.Context) TopicRuleArrayOutput {
	return o
}

func (o TopicRuleArrayOutput) Index(i pulumi.IntInput) TopicRuleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *TopicRule {
		return vs[0].([]*TopicRule)[vs[1].(int)]
	}).(TopicRuleOutput)
}

type TopicRuleMapOutput struct{ *pulumi.OutputState }

func (TopicRuleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*TopicRule)(nil)).Elem()
}

func (o TopicRuleMapOutput) ToTopicRuleMapOutput() TopicRuleMapOutput {
	return o
}

func (o TopicRuleMapOutput) ToTopicRuleMapOutputWithContext(ctx context.Context) TopicRuleMapOutput {
	return o
}

func (o TopicRuleMapOutput) MapIndex(k pulumi.StringInput) TopicRuleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *TopicRule {
		return vs[0].(map[string]*TopicRule)[vs[1].(string)]
	}).(TopicRuleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TopicRuleInput)(nil)).Elem(), &TopicRule{})
	pulumi.RegisterInputType(reflect.TypeOf((*TopicRuleArrayInput)(nil)).Elem(), TopicRuleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*TopicRuleMapInput)(nil)).Elem(), TopicRuleMap{})
	pulumi.RegisterOutputType(TopicRuleOutput{})
	pulumi.RegisterOutputType(TopicRuleArrayOutput{})
	pulumi.RegisterOutputType(TopicRuleMapOutput{})
}
