// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.PolicyPacks.Aws.Rekognition.Inputs
{
    public sealed class StreamProcessorRegionsOfInterestPolygonArgs
    {
        /// <summary>
        /// The value of the X coordinate for a point on a Polygon.
        /// </summary>
        [Input("x")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<double> _mX;

        public double? X => _mX.GetValue("x");

        /// <summary>
        /// The value of the Y coordinate for a point on a Polygon.
        /// </summary>
        [Input("y")]
        #pragma warning disable CS0649 // Field is assigned through deserializer
        private global::Pulumi.Core.UndeferrableValue<double> _mY;

        public double? Y => _mY.GetValue("y");
    }
}
