// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aws.guardduty.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class OrganizationConfigurationFeatureAdditionalConfiguration {
    /**
     * @return The status of the additional configuration that will be configured for the organization. Valid values: `NEW`, `ALL`, `NONE`.
     * 
     */
    private String autoEnable;
    /**
     * @return The name of the additional configuration that will be configured for the organization. Valid values: `EKS_ADDON_MANAGEMENT`.
     * 
     */
    private String name;

    private OrganizationConfigurationFeatureAdditionalConfiguration() {}
    /**
     * @return The status of the additional configuration that will be configured for the organization. Valid values: `NEW`, `ALL`, `NONE`.
     * 
     */
    public String autoEnable() {
        return this.autoEnable;
    }
    /**
     * @return The name of the additional configuration that will be configured for the organization. Valid values: `EKS_ADDON_MANAGEMENT`.
     * 
     */
    public String name() {
        return this.name;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(OrganizationConfigurationFeatureAdditionalConfiguration defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String autoEnable;
        private String name;
        public Builder() {}
        public Builder(OrganizationConfigurationFeatureAdditionalConfiguration defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.autoEnable = defaults.autoEnable;
    	      this.name = defaults.name;
        }

        @CustomType.Setter
        public Builder autoEnable(String autoEnable) {
            this.autoEnable = Objects.requireNonNull(autoEnable);
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        public OrganizationConfigurationFeatureAdditionalConfiguration build() {
            final var _resultValue = new OrganizationConfigurationFeatureAdditionalConfiguration();
            _resultValue.autoEnable = autoEnable;
            _resultValue.name = name;
            return _resultValue;
        }
    }
}
