// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aws.Quicksight.Inputs
{

    public sealed class DashboardDefinitionSheetSheetControlLayoutsConfigurationArgs : global::Pulumi.ResourceArgs
    {
        [Input("gridLayout")]
        public Input<Inputs.GridLayoutArgs>? GridLayout { get; set; }

        public DashboardDefinitionSheetSheetControlLayoutsConfigurationArgs()
        {
        }
        public static new DashboardDefinitionSheetSheetControlLayoutsConfigurationArgs Empty => new DashboardDefinitionSheetSheetControlLayoutsConfigurationArgs();
    }
}
