// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aws.chime.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class VoiceConnectorTerminationState extends com.pulumi.resources.ResourceArgs {

    public static final VoiceConnectorTerminationState Empty = new VoiceConnectorTerminationState();

    @Import(name="callingRegions")
    private @Nullable Output<List<String>> callingRegions;

    public Optional<Output<List<String>>> callingRegions() {
        return Optional.ofNullable(this.callingRegions);
    }

    @Import(name="cidrAllowLists")
    private @Nullable Output<List<String>> cidrAllowLists;

    public Optional<Output<List<String>>> cidrAllowLists() {
        return Optional.ofNullable(this.cidrAllowLists);
    }

    @Import(name="cpsLimit")
    private @Nullable Output<Integer> cpsLimit;

    public Optional<Output<Integer>> cpsLimit() {
        return Optional.ofNullable(this.cpsLimit);
    }

    @Import(name="defaultPhoneNumber")
    private @Nullable Output<String> defaultPhoneNumber;

    public Optional<Output<String>> defaultPhoneNumber() {
        return Optional.ofNullable(this.defaultPhoneNumber);
    }

    @Import(name="disabled")
    private @Nullable Output<Boolean> disabled;

    public Optional<Output<Boolean>> disabled() {
        return Optional.ofNullable(this.disabled);
    }

    @Import(name="region")
    private @Nullable Output<String> region;

    public Optional<Output<String>> region() {
        return Optional.ofNullable(this.region);
    }

    @Import(name="voiceConnectorId")
    private @Nullable Output<String> voiceConnectorId;

    public Optional<Output<String>> voiceConnectorId() {
        return Optional.ofNullable(this.voiceConnectorId);
    }

    private VoiceConnectorTerminationState() {}

    private VoiceConnectorTerminationState(VoiceConnectorTerminationState $) {
        this.callingRegions = $.callingRegions;
        this.cidrAllowLists = $.cidrAllowLists;
        this.cpsLimit = $.cpsLimit;
        this.defaultPhoneNumber = $.defaultPhoneNumber;
        this.disabled = $.disabled;
        this.region = $.region;
        this.voiceConnectorId = $.voiceConnectorId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(VoiceConnectorTerminationState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private VoiceConnectorTerminationState $;

        public Builder() {
            $ = new VoiceConnectorTerminationState();
        }

        public Builder(VoiceConnectorTerminationState defaults) {
            $ = new VoiceConnectorTerminationState(Objects.requireNonNull(defaults));
        }

        public Builder callingRegions(@Nullable Output<List<String>> callingRegions) {
            $.callingRegions = callingRegions;
            return this;
        }

        public Builder callingRegions(List<String> callingRegions) {
            return callingRegions(Output.of(callingRegions));
        }

        public Builder callingRegions(String... callingRegions) {
            return callingRegions(List.of(callingRegions));
        }

        public Builder cidrAllowLists(@Nullable Output<List<String>> cidrAllowLists) {
            $.cidrAllowLists = cidrAllowLists;
            return this;
        }

        public Builder cidrAllowLists(List<String> cidrAllowLists) {
            return cidrAllowLists(Output.of(cidrAllowLists));
        }

        public Builder cidrAllowLists(String... cidrAllowLists) {
            return cidrAllowLists(List.of(cidrAllowLists));
        }

        public Builder cpsLimit(@Nullable Output<Integer> cpsLimit) {
            $.cpsLimit = cpsLimit;
            return this;
        }

        public Builder cpsLimit(Integer cpsLimit) {
            return cpsLimit(Output.of(cpsLimit));
        }

        public Builder defaultPhoneNumber(@Nullable Output<String> defaultPhoneNumber) {
            $.defaultPhoneNumber = defaultPhoneNumber;
            return this;
        }

        public Builder defaultPhoneNumber(String defaultPhoneNumber) {
            return defaultPhoneNumber(Output.of(defaultPhoneNumber));
        }

        public Builder disabled(@Nullable Output<Boolean> disabled) {
            $.disabled = disabled;
            return this;
        }

        public Builder disabled(Boolean disabled) {
            return disabled(Output.of(disabled));
        }

        public Builder region(@Nullable Output<String> region) {
            $.region = region;
            return this;
        }

        public Builder region(String region) {
            return region(Output.of(region));
        }

        public Builder voiceConnectorId(@Nullable Output<String> voiceConnectorId) {
            $.voiceConnectorId = voiceConnectorId;
            return this;
        }

        public Builder voiceConnectorId(String voiceConnectorId) {
            return voiceConnectorId(Output.of(voiceConnectorId));
        }

        public VoiceConnectorTerminationState build() {
            return $;
        }
    }

}
