# When a release occurs, trigger a Lambda that creates issues in downstream consumers of this repo.
name: Release Handler
on:
  release:
    types: [released]
jobs:
  invoke-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke internal-release-handler
        id: invoke
        uses: gagoar/invoke-aws-lambda@v3.3.1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.INTERNAL_RELEASE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.INTERNAL_RELEASE_SECRET_ACCESS_KEY }}
          REGION: us-west-2
          FunctionName: internal-release-handler
          Payload: '{ "repo": "${{ github.event.repository.name }}", "tag_name": "${{ github.event.release.tag_name }}", "url": "${{ github.event.release.html_url }}" }'
          LogType: Tail
      - id: base64
        if: always()
        uses: colpal/actions-base64-decode@v1
        with:
          base64: ${{ fromJSON(steps.invoke.outputs.response).LogResult }}
      - name: Display response
        run: echo "${{ steps.base64.outputs.decoded }}"
        if: always()
