// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aws.wafv2.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class WebAclRuleStatementSizeConstraintStatementFieldToMatchJa3Fingerprint {
    /**
     * @return Match status to assign to the web request if there is insufficient TSL Client Hello information to compute the JA3 fingerprint. Valid values include: `MATCH` or `NO_MATCH`.
     * 
     */
    private String fallbackBehavior;

    private WebAclRuleStatementSizeConstraintStatementFieldToMatchJa3Fingerprint() {}
    /**
     * @return Match status to assign to the web request if there is insufficient TSL Client Hello information to compute the JA3 fingerprint. Valid values include: `MATCH` or `NO_MATCH`.
     * 
     */
    public String fallbackBehavior() {
        return this.fallbackBehavior;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(WebAclRuleStatementSizeConstraintStatementFieldToMatchJa3Fingerprint defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String fallbackBehavior;
        public Builder() {}
        public Builder(WebAclRuleStatementSizeConstraintStatementFieldToMatchJa3Fingerprint defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.fallbackBehavior = defaults.fallbackBehavior;
        }

        @CustomType.Setter
        public Builder fallbackBehavior(String fallbackBehavior) {
            if (fallbackBehavior == null) {
              throw new MissingRequiredPropertyException("WebAclRuleStatementSizeConstraintStatementFieldToMatchJa3Fingerprint", "fallbackBehavior");
            }
            this.fallbackBehavior = fallbackBehavior;
            return this;
        }
        public WebAclRuleStatementSizeConstraintStatementFieldToMatchJa3Fingerprint build() {
            final var _resultValue = new WebAclRuleStatementSizeConstraintStatementFieldToMatchJa3Fingerprint();
            _resultValue.fallbackBehavior = fallbackBehavior;
            return _resultValue;
        }
    }
}
